### ISSUE TITLE
finder.py not finding sids

### ISSUE THREAD

**Issue by CapitalZe** [alpacahq/pylivetrader#110]
I'm trying to run some different, and notably more complex, example algorithms from Quantopian.

When I do, I always receive this same error:

```[2019-07-10 15:35:48.515494] INFO: Algorithm: livetrader start running with backend = alpaca data-frequency = minute
Traceback (most recent call last):
  File "/home/XX-XXX/Desktop/venv/lib/python3.5/site-packages/pylivetrader/assets/finder.py", line 102, in retrieve_asset
    asset = self._asset_cache[sid]
KeyError: 19920

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/XX-XXX/Desktop/venv/bin/pylivetrader", line 10, in <module>
    sys.exit(main())
  File "/home/XX-XXX/Desktop/venv/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/XX-XXX/Desktop/venv/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/XX-XXX/Desktop/venv/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/XX-XXX/Desktop/venv/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/XX-XXX/Desktop/venv/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/XX-XXX/Desktop/venv/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/XX-XXX/Desktop/venv/lib/python3.5/site-packages/pylivetrader/__main__.py", line 161, in run
    algorithm.run(retry=ctx.retry)
  File "/home/XX-XXX/Desktop/venv/lib/python3.5/site-packages/pylivetrader/algorithm.py", line 264, in run
    self.initialize()
  File "/home/XX-XXX/Desktop/venv/lib/python3.5/site-packages/pylivetrader/algorithm.py", line 224, in initialize
    self._initialize(self, *args, **kwargs)
  File "algo1.py", line 14, in initialize
    context.stocks = [sid(19920),sid(32265)] # QQQ & PSQ
  File "/home/XX-XXX/Desktop/venv/lib/python3.5/site-packages/pylivetrader/misc/api_context.py", line 62, in wrapped
    return getattr(algorithm, f.__name__)(*args, **kwargs)
  File "/home/XX-XXX/Desktop/venv/lib/python3.5/site-packages/pylivetrader/algorithm.py", line 473, in sid
    return self.asset_finder.retrieve_asset(sid)
  File "/home/XX-XXX/Desktop/venv/lib/python3.5/site-packages/pylivetrader/assets/finder.py", line 107, in retrieve_asset
    raise SidsNotFound(sids=[sid])
pylivetrader.errors.SidsNotFound: No asset found for sid: 19920.

```

I convert the algorithm files using `!2to3 -w X.py` with no issues.

Why is it that finder.py is not finding the sids which emerge from these example algorithms?

The source for the example algorithm is [here](https://www.quantopian.com/posts/wsj-example-algorithm).

Many thanks!

**Comment by CapitalZe** [comment]
I'm really stuck with this, any pointers or clues would be really appreciated.

**Comment by ttt733** [comment]
Hi @CapitalZe , I'm not sure what could be causing this. I can't imagine that 2to3 would just replace numbers like that, and in the "WSJ Example" source code you linked it uses the correct SIDs. Are you sure that you haven't made any changes to the code yourself?

**Comment by United-T** [comment]
Im having issues as well. Migrated algos over from Catalyst (essentially quantopians zipline) and cannot get my paper trading account to find any sids.

In addition, with the use of symbols you get a similar error saying the asset cannot be bought because it has been delisted.

**Comment by CapitalZe** [comment]
Hi,

I never modified anything in that file. I also never resolved the SIDs problem. Right now I'm stuck on something else, once I overcome that I'll revisit this and post anything I learn.

Apologies for the delay.
