### ISSUE TITLE
ERROR: Executor:

### ISSUE THREAD

**Issue by mrmushfiq** [alpacahq/pylivetrader#132]
Any clue what's going on?
```
[2020-03-04 16:51:00.749385] WARNING: Executor: Continuing execution
[2020-03-04 17:01:00.663772] ERROR: Executor:
Traceback (most recent call last):
  File "c:\users\mrahman\anaconda3\envs\pylivetrader\lib\site-packages\pylivetrader\executor\executor.py", line 67, in wrapper
    func(*args, **kwargs)
  File "c:\users\mrahman\anaconda3\envs\pylivetrader\lib\site-packages\pylivetrader\executor\executor.py", line 88, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "c:\users\mrahman\anaconda3\envs\pylivetrader\lib\site-packages\pylivetrader\misc\events.py", line 218, in handle_data
    dt,
  File "c:\users\mrahman\anaconda3\envs\pylivetrader\lib\site-packages\pylivetrader\misc\events.py", line 237, in handle_data
    self.callback(context, data)
  File "algo3.py", line 259, in my_rebalance
    stock = next(context.MyCandidate)
StopIteration
[2020-03-04 17:01:00.663772] WARNING: Executor: Continuing execution
```

**Comment by shlomikushchi** [comment]
I assume algo3 is the algo code file
what is `next()` ? I don't see `next` in pylivetrader's code, so it's probably your code?
did you migrate it correctly from quantopian/zipline?

**Comment by mrmushfiq** [comment]
I was actually running an example from a blog. You are right. Probably it's not something from pylivealgo. I switched to the Python Trading api instead. So I'm gonna close it. Thanks
