### ISSUE TITLE
Maximum bars error in latest version

### ISSUE THREAD

**Issue by nabeelio** [alpacahq/pylivetrader#155]
I'm requesting 1d history for 200d, and it's throwing an error now, after updating to `0.3.0`. No code changes and downgrading back to `0.2.0` fixes it. Though the error could be in the `alpaca-trade-api` library, the version of that didn't change it seems. I can reopen there if it is.

The call:

```python
self._ohlc_daily = self._data.history(
        self.security,
        ['open', 'close', 'high', 'low'],
        200,
        '1d') \
    .dropna()
```

Logs:
```
[2020-05-18 08:59:52.356279] DEBUG: reversion: sell_queue restored: {'TDOC': Asset(d2eb2ae7-fb5e-47d8-a0bf-ff77f0f47f94, symbol=TDOC, asset_name=TDOC, exchange=NYSE)}
[2020-05-18 08:59:52.357221] INFO: reversion: Creating pipeline
[2020-05-18 08:59:52.375289] DEBUG: reversion: Running before trading starts
[2020-05-18 08:59:53.145132] INFO: pipeline_live.data.alpaca.pricing_loader: chart_range=74
[2020-05-18 09:00:08.771244] INFO: pipeline_live.data.alpaca.pricing_loader: chart_range=221
[2020-05-18 09:00:26.039294] INFO: pipeline_live.data.alpaca.pricing_loader: chart_range=18
[2020-05-18 09:00:47.496312] DEBUG: reversion: Number of candidates to prepare: 87
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 136, in _one_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://data.alpaca.markets/v1/bars/minute?symbols=AAWW&limit=1001&start=2020-05-16&end=2020-05-18
reversion_1  |
During handling of the above exception, another exception occurred:
reversion_1  |
Traceback (most recent call last):
  File "/usr/local/bin/pylivetrader", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/__main__.py", line 222, in run
    algorithm.run(retry=ctx.retry)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 275, in run
    return self.executor.run(retry=retry)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 119, in run
    algo.before_trading_start(self.current_data)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 248, in before_trading_start
    self._before_trading_start(self, data)
  File "reversion.py", line 291, in before_trading_start
    prepare_candidates(context, data)
  File "reversion.py", line 325, in prepare_candidates
    indicators = Indicators(security, data)
  File "reversion.py", line 94, in __init__
    super().__init__(security, data)
  File "/opt/algo/algo/indicator.py", line 32, in __init__
    self.get_data()
  File "/opt/algo/algo/indicator.py", line 43, in get_data
    '1d') \
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/data/bardata.py", line 163, in history
    )[assets] for field in fields
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/data/bardata.py", line 163, in <dictcomp>
    )[assets] for field in fields
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/data/data_portal.py", line 86, in get_history_window
    end_dt=end_dt).swaplevel(
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/data/data_portal.py", line 62, in _get_realtime_bars
    assets, frequency, bar_count=bar_count)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 505, in get_bars
    symbols, 'minute', limit=1000)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 631, in _symbol_bars
    return parallelize(fetch)(symbols)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/misc/parallel_utils.py", line 39, in wrapper
    task_result = task.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 595, in fetch
    limit=limit+1).df[symbol]
  File "/usr/local/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 359, in get_barset
    resp = self.data_get('/bars/{}'.format(timeframe), params)
  File "/usr/local/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 166, in data_get
    'GET', path, data, base_url=base_url, api_version='v1'
  File "/usr/local/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 115, in _request
    return self._one_request(method, url, opts, retry)
  File "/usr/local/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 144, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: maximum 1000 bars per symbol per request
```

Library versions:

```
"alpaca-trade-api": {
    "hashes": [	
        "sha256:60e42308bbfce7f7cd227b5e0dc5c371c783faa3dd58173ea4800d6031201570",
        "sha256:9f3f8a1f678b19754ae70ba61be98e9226e7c72b5a9e6645480555c78228189a"
        ],
    "version": "==0.48"
},

"pylivetrader": {
    "hashes": [
        "sha256:8d6039132818d01728ca3696935410e9218f8f0fdce1106ffa29e6efef733471",
        "sha256:96a128528d34763acbc30f142919c0f60f8491514e74c5773f748f43cb80486e"
    ],
    "version": "==0.3.0"
},
```

**Comment by jeefy** [comment]
Running into the same issue as well.

**Comment by shlomikushchi** [comment]
so, first of all you see the exception
`alpaca_trade_api.rest.APIError: maximum 1000 bars per symbol per request`
that means you must ask for a limited amount.
and yes it, as the exception indicates - it originates from the API (not pylivetrader)

secondly, if you write code in pylivetrader you need to use `context`. not `self`... where is this written? `self._data.history()`

this is the correct way to call data.history():
`data.history(symbol("TDOC"), ['open', 'close', 'high', 'low'], 200, '1d')`

when executing this locally, this is what I get:
![image](https://user-images.githubusercontent.com/7924802/82225212-94f6c600-992d-11ea-9ee1-174f30ab7aef.png)

**Comment by nabeelio** [comment]
The `self` is how I'm referring to a data object for a data indicator, the values I store in a class... that's not relevant to the error. Either way, `data.history()` is being called.

Downgrading the library and no code changes worked. There's an issue with how the request is being put together. If you look at the URL that's generated by the library:

```requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://data.alpaca.markets/v1/bars/minute?symbols=AAWW&limit=1001&start=2020-05-16&end=2020-05-18
```

The value `limit=1001` is being added, even though I'm passing in a value of 200 for 1d. It's not an issue in my code.

**Comment by shlomikushchi** [comment]
could you try creating a clean virtual env just install pylivetrader and try?
I am executing this `data.history(symbol("TDOC"), ['open', 'close', 'high', 'low'], 200, '1d')` with no issues.

**Comment by nabeelio** [comment]
This is a clean virtualenv, it runs in a Docker container that's rebuilt when there are library updates. I'll try to do something from scratch later today if I can get a chance.

@jeefy is also seeing it

**Comment by shlomikushchi** [comment]
another thing for you to check: most dockerfiles do this
`RUN pip install -r requirements.txt`
this line does not know if requirements.txt has changed, hence - does not rebuild the docker image and just use a cached layer. 
meaning - you may update requirements.txt but still use the old packages.

**Comment by shlomikushchi** [comment]
@jeefy if you have more input on the case let me know

**Comment by nabeelio** [comment]
I'm not using the requirements.txt, since it sometimes does have some issues. I don't use `*` versions either, they're all hardcoded, so any changes would get picked up. I use Pipenv, and the installed versions I posted above was from the lock file, which showed the 0.3.0 version is installed.

**Comment by shlomikushchi** [comment]
I need a way to reproduce this in order to debug the api call

**Comment by shlomikushchi** [comment]
I see it.. trying to understand why it happens.

**Comment by nabeelio** [comment]
Ok great, thanks. I'm working on a clean environment to create an example but I guess you're good on that now?

**Comment by shlomikushchi** [comment]
yes. don't need an example for this one.

**Comment by shlomikushchi** [comment]
so I added a fix for this issue. could you make sure it works for you by installing the version from github like so:

`pip install git+https://github.com/alpacahq/pylivetrader`

**Comment by nabeelio** [comment]
I think it looks OK now. I will have it run completely on my paper account when it runs tomorrow morning.

**Comment by jmaslek** [comment]
I just ran the new pip install, then am using data.history([stock], 'price', 20, '1d') and I get the following (I print stock first)

`Equity(25132197-2119-466a-8aff-e157f6e9e0c8 [BXG])
[2020-05-18 18:21:00.961993] ERROR: Executor: maximum 1000 bars per symbol per request
Traceback (most recent call last):
  File "/Users/Jamie/tutorial-env/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 136, in _one_request
    resp.raise_for_status()
  File "/Users/Jamie/tutorial-env/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://data.alpaca.markets/v1/bars/minute?symbols=BXG&limit=1001&start=2020-05-17&end=2020-05-18`

**Comment by nabeelio** [comment]
@jmaslek Can you double-check to see if your local library has this diff?
https://github.com/alpacahq/pylivetrader/commit/5677c7e094b3ccab63031436c2b5c083057338e1

It seems OK on my end with the latest master.

**Comment by jmaslek** [comment]
It did not have that difference.  Lets see if it runs at market open!

**Comment by nabeelio** [comment]
Ah, then it likely hasn't pulled the latest master

**Comment by shlomikushchi** [comment]
@jmaslek install it like this:
`pip install -U git+https://github.com/alpacahq/pylivetrader/`

**Comment by nabeelio** [comment]
Are you going to create a new release soon? These changes really should be on branches and PRs, not directly on master

**Comment by shlomikushchi** [comment]
I will release a version soon when I am not getting any other rejects for the code. 
about branches, generally I agree with your approach.
 currently I support this project alone. 
if others will write code to it ofc we will use branches and PRs
when the code is stable I tag a version. (and we release it to pypi)
most people should install the latest version and not from the master branch. (or dev or any other active branch)
I commit to the master branch (and point others to install from the master branch) when people with usecases different than mine find bugs or issues.

**Comment by nabeelio** [comment]
I didn't run into any issues this morning, and it seems like #152 is fixed for me too

**Comment by nabeelio** [comment]
I saw you released this, thanks, I don't see it on pypi yet. I also just want to make that using the Polygon API is still possible with this? with `use_polygon`?

**Comment by shlomikushchi** [comment]
yes it is
