### ISSUE TITLE
The truth value of a Index is ambiguous

### ISSUE THREAD

**Issue by nabeelio** [alpacahq/pylivetrader#156]
When retrieving the data for multiple assets:

```
context.assets = [symbol("SPY"), symbol("QQQ")]  # just an example
highs = data.history(context.assets, 'high', context.talib_window, "1d")
```

The logs:

```
[2020-05-18 10:02:00.130779] ERROR: Executor: The truth value of a Index is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Traceback (most recent call last):
  File "/Users/nabeelshahzad/dev/nabeelio/algo-trading/pylivetrader/.venv/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 67, in wrapper
    func(*args, **kwargs)
  File "/Users/nabeelshahzad/dev/nabeelio/algo-trading/pylivetrader/.venv/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 88, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/Users/nabeelshahzad/dev/nabeelio/algo-trading/pylivetrader/.venv/lib/python3.6/site-packages/pylivetrader/misc/events.py", line 218, in handle_data
    dt,
  File "/Users/nabeelshahzad/dev/nabeelio/algo-trading/pylivetrader/.venv/lib/python3.6/site-packages/pylivetrader/misc/events.py", line 237, in handle_data
    self.callback(context, data)
  File "momentum.py", line 150, in rebalance
    highs = data.history(context.assets, 'high', context.talib_window, "1d")
  File "/Users/nabeelshahzad/dev/nabeelio/algo-trading/pylivetrader/.venv/lib/python3.6/site-packages/pylivetrader/data/bardata.py", line 126, in history
    if not (assets and fields):
  File "/Users/nabeelshahzad/dev/nabeelio/algo-trading/pylivetrader/.venv/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 1676, in __nonzero__
    .format(self.__class__.__name__))
ValueError: The truth value of a Index is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**Comment by shlomikushchi** [comment]
do you get this every time? this is what I get when calling data for these symbols: 
![image](https://user-images.githubusercontent.com/7924802/82226235-eb183900-992e-11ea-85cf-216959e81b15.png)

do you have a way to reproduce this?

**Comment by nabeelio** [comment]
It looks like it's actually an when it's an `Index`. This is valid syntax on Quantopian. This should do it:

```python
assets: DataFrame = DataFrame([{'symbol': symbol('SPY'), 'some_value': 1}])
assets.set_index('symbol', inplace=True)
hist = data.history(assets.index, 'high', 20, '1d')
```

**Comment by nabeelio** [comment]
Commenting out the erroring lines in `history()` allows it to work, so it just needs to be a more sophisticated check

```python
        # pylivetrader/data/bardata.py::126
        if not (assets and fields):
            return None
```

**Comment by shlomikushchi** [comment]
as you can see in the example I added, I just used the symbol() function and a python list. 
no dataframe manipulations...

**Comment by nabeelio** [comment]
Well, sure, but is this supposed to be compatible with Quantopian? This seems like a very common pattern, I've seen it a few times in different algos on the site. It's retrieving data from the list of assets returned by `Pipeline()`. In full, it looks something like:

```python
context.selected_universe = pipeline_output('screen')
context.assets = context.selected_universe.index

highs = data.history(context.assets, 'high', context.talib_window, "1d")
lows = data.history(context.assets, 'low', context.talib_window, "1d")
closes = data.history(context.assets, 'close', context.market_window, "1d")
```

**Comment by shlomikushchi** [comment]
this is the example code for pipeline usage: 
```py
    for asset in context.output.index:
        short_data = data.history(
            asset, 'price', bar_count=short_periods, frequency="1m")
```
is it not as the example you mentioned?

**Comment by nabeelio** [comment]
That's only retrieving for one asset at a time, not multiple assets at once

**Comment by nabeelio** [comment]
I've changed it to this for now and it works, so you can close this if you want. But it'd be useful to leave a note in the migration guide from Quantopian:

```python
assets = [a for a in context.output.index]
highs = data.history(assets, 'high', 10, '1d')
```

**Comment by shlomikushchi** [comment]
you could just do this: 
`data.history(list(context.output.index), 'price', bar_count=10, frequency="1d")`

just wrap the index with a list() and it works

**Comment by nabeelio** [comment]
Yeah, that works too. Thanks

**Comment by shlomikushchi** [comment]
I added this code into the package. 
try executing with the latest version. no need to wrap with list()
install ftom github directly
