### ISSUE TITLE
APIError: maximum 1000 bars per symbol per request

### ISSUE THREAD

**Issue by spitzbubchen** [alpacahq/pylivetrader#157]
Have started to get the following error:

> (venv) ubuntu@ip-172-31-39-254:~/alpaca$ pylivetrader run algos/penny-stocks/main.py 
> [2020-05-22 16:49:39.227451] INFO: Algorithm: livetrader start running with backend = alpaca data-frequency = minute
> Total number of inital portfolio positions:  0
> [2020-05-22 16:49:40.779800] INFO: algo: 
> Algorithm initialized variables:
>  context.MaxCandidates 30 
>  LowVar 6 
>  HighVar 40
> Get stock data for today...
> [2020-05-22 16:49:40.795947] INFO: pipeline_live.data.alpaca.pricing_loader: chart_range=65
> [2020-05-22 16:49:51.312641] INFO: pipeline_live.data.alpaca.pricing_loader: chart_range=29
> /home/ubuntu/alpaca/venv/lib/python3.6/site-packages/zipline/pipeline/filters/filter.py:382: RuntimeWarning: invalid value encountered in less_equal
>   return (lower_bounds <= data) & (data <= upper_bounds)
> Total number of portfolio positions:  0
> Start rebalance...
> Equity(c50c97c6-535f-42be-97b5-e45f6f3634fa [AIRI])
> [2020-05-22 16:51:01.134001] ERROR: Executor: maximum 1000 bars per symbol per request
> Traceback (most recent call last):
>   File "/home/ubuntu/alpaca/venv/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 136, in _one_request
>     resp.raise_for_status()
>   File "/home/ubuntu/alpaca/venv/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://data.alpaca.markets/v1/bars/minute?symbols=AIRI&limit=1001&start=2020-05-21&end=2020-05-22
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/alpaca/venv/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 67, in wrapper
>     func(*args, **kwargs)
>   File "/home/ubuntu/alpaca/venv/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 88, in every_bar
>     handle_data(algo, current_data, dt_to_use)
>   File "/home/ubuntu/alpaca/venv/lib/python3.6/site-packages/pylivetrader/misc/events.py", line 218, in handle_data
>     dt,
>   File "/home/ubuntu/alpaca/venv/lib/python3.6/site-packages/pylivetrader/misc/events.py", line 237, in handle_data
>     self.callback(context, data)
>   File "main.py", line 239, in my_rebalance
>   File "/home/ubuntu/alpaca/venv/lib/python3.6/site-packages/pylivetrader/data/bardata.py", line 143, in history
>     self.data_frequency,
>   File "/home/ubuntu/alpaca/venv/lib/python3.6/site-packages/pylivetrader/data/data_portal.py", line 86, in get_history_window
>     end_dt=end_dt).swaplevel(
>   File "/home/ubuntu/alpaca/venv/lib/python3.6/site-packages/pylivetrader/data/data_portal.py", line 62, in _get_realtime_bars
>     assets, frequency, bar_count=bar_count)
>   File "/home/ubuntu/alpaca/venv/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 505, in get_bars
>     symbols, 'minute', limit=1000)
>   File "/home/ubuntu/alpaca/venv/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 631, in _symbol_bars
>     return parallelize(fetch)(symbols)
>   File "/home/ubuntu/alpaca/venv/lib/python3.6/site-packages/pylivetrader/misc/parallel_utils.py", line 39, in wrapper
>     task_result = task.result()
>   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
>     return self.__get_result()
>   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
>     raise self._exception
>   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/home/ubuntu/alpaca/venv/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 82, in wrapper
>     return func(*args, **kwargs)
>   File "/home/ubuntu/alpaca/venv/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 595, in fetch
>     limit=limit+1).df[symbol]
>   File "/home/ubuntu/alpaca/venv/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 359, in get_barset
>     resp = self.data_get('/bars/{}'.format(timeframe), params)
>   File "/home/ubuntu/alpaca/venv/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 166, in data_get
>     'GET', path, data, base_url=base_url, api_version='v1'
>   File "/home/ubuntu/alpaca/venv/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 115, in _request
>     return self._one_request(method, url, opts, retry)
>   File "/home/ubuntu/alpaca/venv/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 144, in _one_request
>     raise APIError(error, http_error)
> alpaca_trade_api.rest.APIError: maximum 1000 bars per symbol per request
> [2020-05-22 16:51:01.137649] WARNING: Executor: Continuing execution
>

**Comment by spitzbubchen** [comment]
Did `pip install -U git+https://github.com/alpacahq/pylivetrader/` which fixed the issue.
