### ISSUE TITLE
Unable to install pylivetrader

### ISSUE THREAD

**Issue by jonassharma** [alpacahq/pylivetrader#170]
I have followed the following steps:

$ python3.6 -m venv venv
$ source venv/bin/activate
(venv)$ pip install pylivetrader

It says (venv) $ and according to python --version says: Python 3.6.0 So I should be fine?

However, I do get the following error message after "Downloading zipline"

Does anyone know whats wrong? 

Thank you in advance,
Jonas

Collecting zipline==1.3.0
  Downloading zipline-1.3.0.tar.gz (2.5 MB)
     |████████████████████████████████| 2.5 MB 4.9 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/Jonas/venv/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-zamkr9qu/zipline/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-zamkr9qu/zipline/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-pip-egg-info-5dl1y3oc
         cwd: /private/tmp/pip-install-zamkr9qu/zipline/
    Complete output (152 lines):
    Compiling /tmp/easy_install-oxz2tonq/Cython-3.0a5/Cython/Plex/Scanners.py because it changed.
    Compiling /tmp/easy_install-oxz2tonq/Cython-3.0a5/Cython/Plex/Actions.py because it changed.
    Compiling /tmp/easy_install-oxz2tonq/Cython-3.0a5/Cython/Compiler/Scanning.py because it changed.
    Compiling /tmp/easy_install-oxz2tonq/Cython-3.0a5/Cython/Compiler/Visitor.py because it changed.
    Compiling /tmp/easy_install-oxz2tonq/Cython-3.0a5/Cython/Compiler/FlowControl.py because it changed.
    Compiling /tmp/easy_install-oxz2tonq/Cython-3.0a5/Cython/Runtime/refnanny.pyx because it changed.
    Compiling /tmp/easy_install-oxz2tonq/Cython-3.0a5/Cython/Compiler/FusedNode.py because it changed.
    Compiling /tmp/easy_install-oxz2tonq/Cython-3.0a5/Cython/Tempita/_tempita.py because it changed.
    [1/8] Cythonizing /tmp/easy_install-oxz2tonq/Cython-3.0a5/Cython/Compiler/FlowControl.py
    [2/8] Cythonizing /tmp/easy_install-oxz2tonq/Cython-3.0a5/Cython/Compiler/FusedNode.py
    [3/8] Cythonizing /tmp/easy_install-oxz2tonq/Cython-3.0a5/Cython/Compiler/Scanning.py
    [4/8] Cythonizing /tmp/easy_install-oxz2tonq/Cython-3.0a5/Cython/Compiler/Visitor.py
    [5/8] Cythonizing /tmp/easy_install-oxz2tonq/Cython-3.0a5/Cython/Plex/Actions.py
    [6/8] Cythonizing /tmp/easy_install-oxz2tonq/Cython-3.0a5/Cython/Plex/Scanners.py
    [7/8] Cythonizing /tmp/easy_install-oxz2tonq/Cython-3.0a5/Cython/Runtime/refnanny.pyx
    [8/8] Cythonizing /tmp/easy_install-oxz2tonq/Cython-3.0a5/Cython/Tempita/_tempita.py
    Unable to find pgen, not compiling formal grammar.
    warning: no files found matching 'Doc/*'
    warning: no files found matching '*.pyx' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Debugger/Tests'
    warning: no files found matching '*.pxd' under directory 'Cython/Utility'
    warning: no files found matching 'pyximport/README'
    ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
    ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
    ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
    ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
    ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
    ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
    ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
    ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
    ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
    ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
    ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
    ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
    ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
    ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
    ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
    ld: warning: ignoring file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/lib/libSystem.tbd
    
    Installed /private/tmp/pip-install-zamkr9qu/zipline/.eggs/Cython-3.0a5-py3.6-macosx-10.6-intel.egg
    Searching for numpy>=1.11.1
    Reading https://pypi.python.org/simple/numpy/
    Downloading https://files.pythonhosted.org/packages/f1/2c/717bdd12404c73ec0c8c734c81a0bad7048866bc36a88a1b69fd52b01c07/numpy-1.19.0.zip#sha256=76766cc80d6128750075378d3bb7812cf146415bd29b588616f72c943c00d598
    Best match: numpy 1.19.0
    Processing numpy-1.19.0.zip
    Writing /tmp/easy_install-y2ffskou/numpy-1.19.0/setup.cfg
    Running numpy-1.19.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-y2ffskou/numpy-1.19.0/egg-dist-tmp-3_vb8ot6
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/_philox.pyx
    Traceback (most recent call last):
      File "/tmp/easy_install-y2ffskou/numpy-1.19.0/tools/cythonize.py", line 59, in process_pyx
        from Cython.Compiler.Version import version as cython_version
    ModuleNotFoundError: No module named 'Cython'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/easy_install-y2ffskou/numpy-1.19.0/tools/cythonize.py", line 235, in <module>
        main()
      File "/tmp/easy_install-y2ffskou/numpy-1.19.0/tools/cythonize.py", line 231, in main
        find_process_files(root_dir)
      File "/tmp/easy_install-y2ffskou/numpy-1.19.0/tools/cythonize.py", line 222, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/tmp/easy_install-y2ffskou/numpy-1.19.0/tools/cythonize.py", line 188, in process
        processor_function(fromfile, tofile)
      File "/tmp/easy_install-y2ffskou/numpy-1.19.0/tools/cythonize.py", line 64, in process_pyx
        raise OSError('Cython needs to be installed in Python as a module')
    OSError: Cython needs to be installed in Python as a module
    Running from numpy source directory.
    /tmp/easy_install-y2ffskou/numpy-1.19.0/setup.py:460: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Traceback (most recent call last):
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 278, in run
        return func()
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-y2ffskou/numpy-1.19.0/setup.py", line 489, in <module>
      File "/tmp/easy_install-y2ffskou/numpy-1.19.0/setup.py", line 469, in setup_package
      File "/tmp/easy_install-y2ffskou/numpy-1.19.0/setup.py", line 274, in generate_cython
        'conda-build-script.py')  # win
    RuntimeError: Running cythonize failed!
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-zamkr9qu/zipline/setup.py", line 323, in <module>
        **conditional_arguments
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/Jonas/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/Jonas/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/Users/Jonas/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 695, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1101, in run_setup
        run_setup(setup_script, args)
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 251, in run_setup
        raise
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 100, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 100, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 169, in save_modules
        saved_exc.resume()
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 144, in resume
        six.reraise(type, exc, self._tb)
      File "/Users/Jonas/venv/lib/python3.6/site-packages/pkg_resources/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 157, in save_modules
        yield saved
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 198, in setup_context
        yield
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 248, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 278, in run
        return func()
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 246, in runner
        _execfile(setup_script, ns)
      File "/Users/Jonas/venv/lib/python3.6/site-packages/setuptools/sandbox.py", line 47, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-y2ffskou/numpy-1.19.0/setup.py", line 489, in <module>
      File "/tmp/easy_install-y2ffskou/numpy-1.19.0/setup.py", line 469, in setup_package
      File "/tmp/easy_install-y2ffskou/numpy-1.19.0/setup.py", line 274, in generate_cython
        'conda-build-script.py')  # win
    RuntimeError: Running cythonize failed!
    Cythonizing sources
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by shlomikushchi** [comment]
Hi.
it looks like you need cython installed?
what python are you using? 
it seems to have happend during the installation of zipline.
so it's the package we "wrap" not our package.
maybe you need a clean python 3.6 installation. I recommend 3.6.10. that's the one I work with

**Comment by jonassharma** [comment]
Installing Cython seems to have worked. Although I encountered an error with bcolz, but I followed the directions in the thread below me to fix it. Thank you!
