### ISSUE TITLE
Error in smoke test

### ISSUE THREAD

**Issue by ac223028** [alpacahq/pylivetrader#188]
I have been running in to this error whenever I run a smoke test:

`AttributeError: 'Algorithm' object has no attribute 'backend_options'`

I am running a pipeline like this:
`output = context.pipeline_output('pipeline') # This is the line pylivetrader has a problem with I think.`

Here is the full error message:
```
Traceback (most recent call last):
  File "D:/Trading/CrowsSoldiers/src/smoke_CrowsV3.py", line 15, in <module>
    test_algo()
  File "D:/Trading/CrowsSoldiers/src/smoke_CrowsV3.py", line 7, in test_algo
    harness.run_smoke(algo)
  File "D:\Trading\CrowsSoldiers\venv\lib\site-packages\pylivetrader\testing\smoke\harness.py", line 68, in run_smoke
    a.run()
  File "D:\Trading\CrowsSoldiers\venv\lib\site-packages\pylivetrader\algorithm.py", line 275, in run
    return self.executor.run(retry=retry)
  File "D:\Trading\CrowsSoldiers\venv\lib\site-packages\pylivetrader\executor\executor.py", line 119, in run
    algo.before_trading_start(self.current_data)
  File "D:\Trading\CrowsSoldiers\venv\lib\site-packages\pylivetrader\algorithm.py", line 248, in before_trading_start
    self._before_trading_start(self, data)
  File "D:\Trading\CrowsSoldiers\src\PLTCrowsSoldiersV3.py", line 232, in before_trading_start
    output = context.pipeline_output('pipeline')  # TODO
  File "D:\Trading\CrowsSoldiers\venv\lib\site-packages\pylivetrader\algorithm.py", line 1085, in pipeline_output
    self._make_sure_credentials_are_set()
  File "D:\Trading\CrowsSoldiers\venv\lib\site-packages\pylivetrader\algorithm.py", line 1104, in _make_sure_credentials_are_set
    if self.backend_options:
AttributeError: 'Algorithm' object has no attribute 'backend_options'

Process finished with exit code 1
```

**Comment by shlomikushchi** [comment]
Hi, when running a smoke test you are supposed to use a `pipeline_hook` 
then in `pipeline_output` this will be called and you will never reach this error:
![image](https://user-images.githubusercontent.com/7924802/92409004-dbc03400-f147-11ea-888a-b5c4fb5d436b.png)

**Comment by shlomikushchi** [comment]
this is a simple way of doing that:
![image](https://user-images.githubusercontent.com/7924802/92409030-f4304e80-f147-11ea-937d-6c7c0290a3af.png)

you could find it in `smoke_pipelinelive.py` under the sample folder

**Comment by camelpac** [comment]
closing due to lack of activity

**Comment by vinceperkins** [comment]
Hi All,

What is the best way to run the smoketest file? I have used pytest, but I don't know how to display the `log.info()` comments within the algo file. Is there a way to read the log output from the smoke test? Thank you.
