### ISSUE TITLE
Issue with algorithm smoke testing

### ISSUE THREAD

**Issue by samatix** [alpacahq/pylivetrader#189]
Hi, 

There is an issue with smoke testing because of the simulator's `get_bar()` [method](https://github.com/alpacahq/pylivetrader/blob/bbbd077e804feef0b7136e145b3f1e8c696137ea/pylivetrader/testing/smoke/backend.py#L238) doesn't have the same signature as the [base backend class](https://github.com/alpacahq/pylivetrader/blob/bbbd077e804feef0b7136e145b3f1e8c696137ea/pylivetrader/backend/base.py#L82).
 
To reproduce run the example script in examples/MACD/macd_example.py, you'll get the following error: 

```[2020-09-13 09:56:37.697968] ERROR: Executor: get_bars() got an unexpected keyword argument 'end_dt'
Traceback (most recent call last):
  File "/Users/aennassiri/opensource/pylivetrader/pylivetrader/executor/executor.py", line 67, in wrapper
    func(*args, **kwargs)
  File "/Users/aennassiri/opensource/pylivetrader/pylivetrader/executor/executor.py", line 88, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/Users/aennassiri/opensource/pylivetrader/pylivetrader/misc/events.py", line 218, in handle_data
    dt,
  File "/Users/aennassiri/opensource/pylivetrader/pylivetrader/misc/events.py", line 237, in handle_data
    self.callback(context, data)
  File "/Users/aennassiri/opensource/pylivetrader/pylivetrader/algorithm.py", line 236, in handle_data
    self._handle_data(self, data)
  File "/Users/aennassiri/opensource/pylivetrader/examples/MACD/macd_example.py", line 35, in handle_data
    context.asset, 'price', bar_count=short_periods, frequency="1m")
  File "/Users/aennassiri/opensource/pylivetrader/pylivetrader/data/bardata.py", line 148, in history
    self.data_frequency,
  File "/Users/aennassiri/opensource/pylivetrader/pylivetrader/data/data_portal.py", line 86, in get_history_window
    end_dt=end_dt).swaplevel(
  File "/Users/aennassiri/opensource/pylivetrader/pylivetrader/data/data_portal.py", line 62, in _get_realtime_bars
    assets, frequency, bar_count=bar_count, end_dt=end_dt)
TypeError: get_bars() got an unexpected keyword argument 'end_dt'
[2020-09-13 09:56:37.698173] WARNING: Executor: Continuing execution
```
I'm issuing a PR to correct the issue and add unit testing for the smoke tester. 

Thanks
Ayoub

**Comment by shlomikushchi** [comment]
thanks. fixed here: https://github.com/alpacahq/pylivetrader/commit/078ae08393d8a144f266f5edf9c3d41d4c0f324a
also there was another spot to fix so did it in another commit

**Comment by samatix** [comment]
thanks @shlomikushchi
