### ISSUE TITLE
VXX symbol is not tradable in paper trading mode

### ISSUE THREAD

**Issue by dsinyakov** [alpacahq/pylivetrader#192]
**Steps to reproduce**

in pylivetrader shell execute the following
```*** pylivetrader shell ***
In [1]: symbol('VXX')
Out[1]: Asset(f39bb659-b994-4b94-b791-16e979ccddbe, symbol=VXX, asset_name=VXX, exchange=BATS)
In [2]: data.can_trade([symbol('VXX')])
Out[2]: 
Equity(f39bb659-b994-4b94-b791-16e979ccddbe [VXX])    False
dtype: bool
```
**Expected result**
Active and tradable VXX is returned with sid='273b92cc-8a5d-459a-81bd-981d8ed5f89a' 

**Additional context**
If I hardcode the active one that I get trough alpaca_trade_api
```alpaca_assets = api.list_assets()
my_symbol = 'VXX'
my_sid = [(asset.id, asset.status) for asset in alpaca_assets if asset.symbol == my_symbol]
my_sid
[('273b92cc-8a5d-459a-81bd-981d8ed5f89a', 'active'),
 ('f39bb659-b994-4b94-b791-16e979ccddbe', 'inactive')]
```
the order still executes for inactive symbol. Which then makes rebalancing in my algo impossible, as order_target_percent method that I use returns incorrect amount of VXX as its checking against active sid.

**Comment by shlomikushchi** [comment]
Hi, this is a duplicate issue: https://github.com/alpacahq/pylivetrader/issues/178
but specifically in this case, VXX is not trade-able.
using the API get_asset gives this for VXX:

https://github.com/alpacahq/pylivetrader/issues/178
![image](https://user-images.githubusercontent.com/7924802/93484718-eda19400-f90a-11ea-9a9d-e288c0df3272.png)

**Comment by dsinyakov** [comment]
@shlomikushchi I understand VXX returned by symbol method is not tradable. I show exactly that in logs. The point is, symbol  method should return the one that is tradable.

**Comment by dsinyakov** [comment]
Its the same situation with "TSLA" symbol now

**Comment by shlomikushchi** [comment]
did you pull the latest code from the master branch?

**Comment by dsinyakov** [comment]
@shlomikushchi No, I was still on 0.5.0 version. And it was just for one day. Now TSLA is tradable again.

I have now upgraded to 0.5.1 version and `can_trade` method now identifies VXX symbol as tradable. While that address the issue I filed, I wonder if [the fix](https://github.com/alpacahq/pylivetrader/pull/193) just masks the symptom, since the ticker liveness check has been removed, what we do is essentially say that inactive VXX is now tradable? Does it have any implications when to live endpoint?

What I mean is for the VXX `can_trade` I would expect to see this:
```
Equity(273b92cc-8a5d-459a-81bd-981d8ed5f89a [VXX])    True
```
since VXX with `sid 273b92cc-8a5d-459a-81bd-981d8ed5f89a` is **active**.

But what I get right now is:
```
Equity(f39bb659-b994-4b94-b791-16e979ccddbe [VXX])    True
```
But VXX with `sid f39bb659-b994-4b94-b791-16e979ccddbe` is **inactive**

Thank you for your continued effort to fix this.

**Comment by shlomikushchi** [comment]
so this is, I think, beyond the scope of this package.
it's an api issue - the api is `get_asset(<asset_name>)` 
assuming there's one asset with unique name is reasonable.

you should file this issue here (it's a server side issue): https://forum.alpaca.markets/c/market-data/16

**Comment by shlomikushchi** [comment]
The fix I've made is removing redundant checks. 
if the broker says the asset is tradable, and the market is open - that's enough

the reason it failed is a random chance, since the 2 VXX assets had a specific order on the iteration made in the code.
it could have been easily the other way around, if the order received was backwards. (and of course, there's no way controlling the order of the assets received)

**Comment by dsinyakov** [comment]
@shlomikushchi get_asset api returns the correct asset for VXX which is active and tradable
```
asset = api.get_asset('VXX')
asset

Asset({   'class': 'us_equity',
    'easy_to_borrow': False,
    'exchange': 'BATS',
    'id': '273b92cc-8a5d-459a-81bd-981d8ed5f89a',
    'marginable': True,
    'name': 'iPath Series B S&P 500 VIX Short-Term Futures ETN',
    'shortable': False,
    'status': 'active',
    'symbol': 'VXX',
    'tradable': True})
```
The order here is not important. I think you need expect multiple assets and filter them based on both **status** and **tradable** params.

VXX that is returned right now in pylivetrader is by mistake considered tradable

```
In [3]: data.can_trade([symbol('VXX')])
Out[3]: 
Equity(f39bb659-b994-4b94-b791-16e979ccddbe [VXX])    True
dtype: bool
```
while through API its neither active nor tradable
```
asset = api.get_asset('f39bb659-b994-4b94-b791-16e979ccddbe')
asset

Asset({   'class': 'us_equity',
    'easy_to_borrow': False,
    'exchange': 'BATS',
    'id': 'f39bb659-b994-4b94-b791-16e979ccddbe',
    'marginable': False,
    'name': 'iPath Series B S&P 500 VIX Short-Term Futures ETN',
    'shortable': False,
    'status': 'inactive',
    'symbol': 'VXX',
    'tradable': False})
```

**Comment by dsinyakov** [comment]
oh and by the way when you place an order on VXX that passes tradable check now (id = 'f39bb659-b994-4b94-b791-16e979ccddbe') you get the following warning
```
[2020-09-25 13:31:10.861262] WARNING: Algorithm: Cannot place order for VXX, as it is not tradable.
```

**Comment by shlomikushchi** [comment]
The way pylivetrader handles assets is like this:
* get all us equities from the api
* iterate them and wrap with Equity object
* store in cache
* now work against cache

The only way I'm thinking of right now to handle this is avoid caching untradable equities. this will resolve this issue.
but may cause other issues, so I need to think about this a bit. or maybe find another solution

**Comment by shlomikushchi** [comment]
This PR is what we've discussed before.
I will not include untradable assets in the asset list.
this should resolve issues of duplicated symbols in the asset list.

I will not merge it immediately, I want it tested a bit first.
so, if you could use the code and see it answers the issue that would be great.
if anyone else sees that too, please test it with your paper accounts.

to install directly from this branch you could do this:

`pip install git+https://github.com/alpacahq/pylivetrader@untradable_assets`

**Comment by dsinyakov** [comment]
I missed last update. I will test this in next couple days starting today

**Comment by dsinyakov** [comment]
Hit roadblock while testing. Was there data.history API changes?

```[2020-10-20 13:31:06.783492] ERROR: Executor: Parser must be a string or character stream, not int
Traceback (most recent call last):
  File "/Users/beastie/repo/experimental/alpaca/venv/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 67, in wrapper
    func(*args, **kwargs)
  File "/Users/beastie/repo/experimental/alpaca/venv/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 88, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/Users/beastie/repo/experimental/alpaca/venv/lib/python3.6/site-packages/pylivetrader/misc/events.py", line 218, in handle_data
    dt,
  File "/Users/beastie/repo/experimental/alpaca/venv/lib/python3.6/site-packages/pylivetrader/misc/events.py", line 237, in handle_data
    self.callback(context, data)
  File "algo.py", line 44, in trade
    mavg_f = data.history(stock, 'price', attributes['ma_f'], '1d').mean()
  File "/Users/beastie/repo/experimental/alpaca/venv/lib/python3.6/site-packages/pylivetrader/data/bardata.py", line 147, in history
    self.data_frequency,
  File "/Users/beastie/repo/experimental/alpaca/venv/lib/python3.6/site-packages/pylivetrader/data/data_portal.py", line 86, in get_history_window
    end_dt=end_dt).swaplevel(
  File "/Users/beastie/repo/experimental/alpaca/venv/lib/python3.6/site-packages/pylivetrader/data/data_portal.py", line 62, in _get_realtime_bars
    assets, frequency, bar_count=bar_count, end_dt=end_dt)
  File "/Users/beastie/repo/experimental/alpaca/venv/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 547, in get_bars
    limit=bar_count)
  File "/Users/beastie/repo/experimental/alpaca/venv/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 598, in _fetch_bars_from_api
    result = parallelize(self._fetch_bars_from_api_internal)(args)
  File "/Users/beastie/repo/experimental/alpaca/venv/lib/python3.6/site-packages/pylivetrader/misc/parallel_utils.py", line 42, in wrapper
    task_result = task.result()
  File "/Users/beastie/.pyenv/versions/3.6.11/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/Users/beastie/.pyenv/versions/3.6.11/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/beastie/.pyenv/versions/3.6.11/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/beastie/repo/experimental/alpaca/venv/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 693, in _fetch_bars_from_api_internal
    return wrapper()
  File "/Users/beastie/repo/experimental/alpaca/venv/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 85, in wrapper
    return func(*args, **kwargs)
  File "/Users/beastie/repo/experimental/alpaca/venv/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 670, in wrapper
    int(to.timestamp()) * 1000
  File "/Users/beastie/repo/experimental/alpaca/venv/lib/python3.6/site-packages/alpaca_trade_api/polygon/rest.py", line 204, in historic_agg_v2
    to=fix_daily_bar_date(format_date_for_api_call(to), timespan)
  File "/Users/beastie/repo/experimental/alpaca/venv/lib/python3.6/site-packages/alpaca_trade_api/polygon/rest.py", line 65, in fix_daily_bar_date
    date = dateutil.parser.parse(date)
  File "/Users/beastie/repo/experimental/alpaca/venv/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1374, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/Users/beastie/repo/experimental/alpaca/venv/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 646, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/Users/beastie/repo/experimental/alpaca/venv/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 725, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/Users/beastie/repo/experimental/alpaca/venv/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 207, in split
    return list(cls(s))
  File "/Users/beastie/repo/experimental/alpaca/venv/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 76, in __init__
    '{itype}'.format(itype=instream.__class__.__name__))
TypeError: Parser must be a string or character stream, not int
```

**Comment by shlomikushchi** [comment]
I see it, I will fix it soon

**Comment by shlomikushchi** [comment]
Hi, did a fix in the alpaca-trade-api. you need to install that specific branch since it will take some time until it will be in the master branch. just remember to switch back once it does.
do this: 
`pip install git+https://github.com/alpacahq/alpaca-trade-api-python@avoid_changing_date_as_ints`

**Comment by dsinyakov** [comment]
@shlomikushchi I have tested the fix for multiple days and it looks good to me.

**Comment by shlomikushchi** [comment]
great thanks
