### ISSUE TITLE
NotImplementedError: Index._join_level on non-unique index is not implemented

### ISSUE THREAD

**Issue by Nicosunaa** [alpacahq/pylivetrader#200]
Hi, I getting an error every time I tried to run my algo using "pylivetrader run -f algo.py". I was not getting this error before but I started getting after installing pylivetrader version 0.5.1 but even as I installed  back version 0.5.0 I still getting the same error.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 673, in _fetch_bars_from_api_internal
    return wrapper()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 85, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 659, in wrapper
    end=to.isoformat()).df[symbols]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/frame.py", line 2133, in __getitem__
    return self._getitem_array(key)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/frame.py", line 2177, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/indexing.py", line 1250, in _convert_to_indexer
    obj, kind=self.name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 1798, in _convert_listlike_indexer
    _, indexer = self.reindex(keyarr, level=level)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 1892, in reindex
    keep_order=False)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3299, in _join_level
    raise NotImplementedError('Index._join_level on non-unique index '
NotImplementedError: Index._join_level on non-unique index is not implemented
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/pylivetrader", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/__main__.py", line 277, in run
    algorithm.run(retry=ctx.retry)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 275, in run
    return self.executor.run(retry=retry)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 119, in run
    algo.before_trading_start(self.current_data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 248, in before_trading_start
    self._before_trading_start(self, data)
  File "main.py", line 49, in before_trading_start
    context.longs_weights = my_compute_weights(context, data)
  File "main.py", line 125, in my_compute_weights
    prices = data.history(context.longs, 'price', 15, '1d')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/data/bardata.py", line 148, in history
    self.data_frequency,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/data/data_portal.py", line 86, in get_history_window
    end_dt=end_dt).swaplevel(
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/data/data_portal.py", line 62, in _get_realtime_bars
    assets, frequency, bar_count=bar_count, end_dt=end_dt)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 527, in get_bars
    limit=bar_count)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 596, in _fetch_bars_from_api
    self._fetch_bars_from_api_internal)(args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/misc/parallel_utils.py", line 60, in wrapper
    return pool.map(mapfunc, args_list)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
NotImplementedError: Index._join_level on non-unique index is not implemented

**Comment by shlomikushchi** [comment]
Hi, could you provide a code example I could execute locally so I could try see this error locally?

**Comment by Nicosunaa** [comment]
import numpy as np
import logbook
import alpaca_trade_api as tradeapi
from pylivetrader.api import (attach_pipeline,
                              date_rules,
                              time_rules,
                              order_target_percent,
                              get_open_orders,
                              pipeline_output,
                              get_datetime,
                              schedule_function,
                              cancel_order)
from zipline.pipeline import Pipeline
from pipeline_live.data.alpaca.pricing import USEquityPricing
from pipeline_live.data.iex.fundamentals import IEXCompany
from pipeline_live.data.alpaca.factors import (RSI,
                                               AverageDollarVolume,
                                               ExponentialWeightedMovingAverage,
                                               MovingAverageConvergenceDivergenceSignal)
from scipy.optimize import minimize
from scipy.stats import norm

api = tradeapi.REST(api_version='v2')

# Account Information
account = api.get_account()
print(account)

# Log information
log = logbook.Logger('algo')

def record(*args, **kwargs):
    print('args={}, kwargs={}'.format(args, kwargs))


def before_trading_start(context, data):
    # context.age is to remember some age of positions
    if not hasattr(context, 'age') or not context.age:
        context.age = {}

    today = get_datetime().floor('1D')
    last_date = getattr(context, 'last_date', None)

    # check if it run today
    if today != last_date:
        context.my_pipeline = pipeline_output('my_pipeline')
        # Longs
        context.longs = context.my_pipeline[context.my_pipeline['Longs']].index
        # Longs weights
        context.longs_weights = my_compute_weights(context, data)
        context.last_date = today


def initialize(context):
    schedule_function(my_rebalance, date_rules.every_day(), time_rules.market_close(minutes=30))

    schedule_function(selling, date_rules.every_day(), time_rules.market_open(hours=1))
    schedule_function(selling, date_rules.every_day(), time_rules.market_close(minutes=30))

    schedule_function(record_vars, date_rules.every_day(), time_rules.market_close())
    schedule_function(cancel_open_orders, date_rules.every_day(), time_rules.market_close(minutes=5))

    my_pipe = make_pipeline()
    context.attach_pipeline(my_pipe, 'my_pipeline')


def make_pipeline():
    # Step 1: Sector
    biotech_industry = ~IEXCompany.industry.latest.matches('Biotechnology')
    lifesci_industry = ~IEXCompany.industry.latest.matches('Life')
    pharma_industry = ~IEXCompany.industry.latest.matches('Pharmaceutical')
    renawable_industry = ~IEXCompany.industry.latest.matches('Renewable')

    industry_lim = biotech_industry | pharma_industry | renawable_industry | lifesci_industry

    # Step 2: Price
    latest_close = USEquityPricing.close.latest
    high_price_lim = latest_close <= 40
    low_price_lim = latest_close >= 1
    price_lim = high_price_lim & low_price_lim

    # Step 3: Volume
    dollar_volume_30D = AverageDollarVolume(window_length=30, mask= price_lim&industry_lim)
    dollar_volume_1D = AverageDollarVolume(window_length=1, mask= price_lim&industry_lim)
    volume_lim = dollar_volume_1D >= dollar_volume_30D

    universe = price_lim & volume_lim & industry_lim
    # Step 5: EWMA
    EWMA_15D = ExponentialWeightedMovingAverage(inputs=[USEquityPricing.close], window_length=15, decay_rate=0.94, mask=universe)
    EWMA_30D = ExponentialWeightedMovingAverage(inputs=[USEquityPricing.close], window_length=30, decay_rate=0.94, mask=universe)

    # Step 6: MACD
    MACD = EWMA_15D - EWMA_30D
    MACD_signal = MovingAverageConvergenceDivergenceSignal(inputs=[USEquityPricing.close], fast_period=15, slow_period=30, signal_period=9, mask=universe)
    MACD_diff = MACD - MACD_signal
    MACD_abs_diff = MACD_diff.abs()
    high_MACD_diff = MACD_abs_diff.percentile_between(91, 100)

    MACD_long = MACD < MACD_signal

    # Step 7: RSI
    RSI_15D = RSI(inputs=[USEquityPricing.close], window_length=15, mask=universe)

    RSI_long = RSI_15D < 70

    # Step 8: Securities to Trade
    longs = MACD_long & RSI_long
    securities_to_trade = longs

    # Step 9: Alpha Factors
    testing_factor1 = MACD_diff.rank(mask=universe, method='average')

    testing_factor = testing_factor1

    # testing_quantiles = testing_factor.quantiles(2)

    return Pipeline(columns={'Longs': longs,
                             'testing_factor': testing_factor},
                    screen= securities_to_trade & high_MACD_diff)


def my_compute_weights(context, data):
    if len(context.longs) == 0:
        longs_weight = 0
    else:
        prices = data.history(context.longs, 'price', 15, '1d')
        prices = prices.sort_index(ascending=False)
        prices.columns = map(lambda x: x.symbol, prices.columns)

        daily_returns = np.log(prices / prices.shift(-1)).dropna()
        mean_returns = daily_returns.mean()
        cov_matrix = daily_returns.cov()

        conf_level = 0.05
        var_max = 0.027

        def get_ret_vol_sr(weights):
            weights = np.array(weights)
            ret = np.sum(mean_returns * weights) * 252
            vol = np.sqrt(np.dot(np.transpose(weights), np.dot(cov_matrix * 252, weights)))
            sr = ret / vol
            return np.array([ret, vol, sr])

        def neg_sharpe(weights):
            return get_ret_vol_sr(weights)[2] * (-1)

        def constraint_sum(weights):
            return np.sum(weights) - 1

        def constraint_risk(weights):
            ret = np.sum(mean_returns * weights) * 252
            vol = np.sqrt(np.dot(np.transpose(weights), np.dot(cov_matrix * 252, weights)))
            invst = (1 + ret)
            cutoff = norm.ppf(conf_level, invst, vol)
            var95pct = 1 - cutoff
            return -var95pct + var_max

        def bounds_():
            lst = []
            for security in context.longs:
                lst.append((0, 1))
            return lst

        bounds = tuple(bounds_())

        def init_guess_():
            lst = []
            for security in context.longs:
                lst.append(0.25)
            return lst

        init_guess = init_guess_()

        cons = ({'type': 'eq', 'fun': constraint_sum},
                {'type': 'ineq', 'fun': constraint_risk})

        opt_results = minimize(neg_sharpe, init_guess, method='SLSQP', bounds=bounds, constraints=cons)
        weights = opt_results['x']

        longs_weight = np.nan_to_num(weights)

    return (longs_weight)


def my_rebalance(context, data):
    open_orders = get_open_orders()

    for security in context.portfolio.positions:
        if security not in context.longs and data.can_trade(security):
            order_target_percent(security, 0)

    count = 0
    for security in context.longs:
        if data.can_trade(security) and security not in open_orders:
            if security == context.longs[count]:
                # cash_available = context.portfolio.cash
                order_target_percent(security, context.longs_weights[count])
                count = count + 1


def selling(context, data):
    stoplosspct = 0.005
    takeprofitpct = 1

    open_orders = get_open_orders()

    for security in context.longs:
        if data.can_trade(security) and security not in open_orders:
            cost_share = context.portfolio.positions[security].cost_basis
            price_share = data.current(security, 'price')

            stop_loss_price = cost_share - cost_share * stoplosspct
            if price_share < stop_loss_price:
                order_target_percent(security, 0)

            profit_price = cost_share + cost_share * takeprofitpct
            if price_share > profit_price:
                order_target_percent(security, 0)


def record_vars(context, data):
    long_amount = 0

    for security in context.portfolio.positions.values():
        if security.amount > 0:
            long_amount += 1

    record(Portafolio_value=context.portfolio.portfolio_value)
    record(Positions=long_amount)
    record(Cash_available=context.portfolio.cash)
    record(Leverage=context.account.leverage)

def log_open_orders():
    open_orders = get_open_orders()
    if len(open_orders) == 0:
        return
    for stock, orders in open_orders.items():
        for o in orders:
            message = 'Found open order for {amount} shares in {stock}'
            log.info(message.format(amount=o.amount, stock=stock))

def cancel_open_orders(context, data):
    open_orders = get_open_orders()
    if len(open_orders) == 0:
        return
    for stock, orders in open_orders.items():
        for o in orders:
            message = 'Order for {amount} shares of {stock} was not filled. Canceling order'
            log.info(message.format(amount=o.amount, stock=stock))
            if 0 < o.amount:
                cancel_order(o)

**Comment by Nicosunaa** [comment]
is there a way I could send it to you? I tried to paste it in here but it gets super messy

**Comment by shlomikushchi** [comment]
Hi, you should use the backtick notation like this:
![image](https://user-images.githubusercontent.com/7924802/95592587-85e5f100-0a51-11eb-9c4f-a353fb25c89c.png)

it will result in:

```py

your code here

```

**Comment by camelpac** [comment]
closing due to lack of activity
