### ISSUE TITLE
Algorithm not working when computing weights with scipy function

### ISSUE THREAD

**Issue by Nicosunaa** [alpacahq/pylivetrader#205]
Hi,

My algorithm was working normally until I started using Scipy minimization function to compute the portfolio weights. I used the same method in quantopian and I was not getting any problems running the back test, which makes me wonder if pylivetrader does not support scipy.

**Comment by shlomikushchi** [comment]
Hi, 
pylivetrader runs on your computer, you can install anything you want.
put a breakpoint in your code and see what is it

**Comment by shlomikushchi** [comment]
you could also write a code example here, maybe I will have an idea what is wrong

**Comment by Nicosunaa** [comment]
I'm not getting any errors when I run the code but it is not submitting orders as I used to do before. Here is the code:

`import numpy as np
import pandas as pd
import logbook
import alpaca_trade_api as tradeapi
from pylivetrader.api import (attach_pipeline,
                              date_rules,
                              time_rules,
                              order_target_percent,
                              order_target_value,
                              get_open_orders,
                              pipeline_output,
                              get_datetime,
                              schedule_function,
                              cancel_order)
from zipline.pipeline import Pipeline
from pipeline_live.data.alpaca.pricing import USEquityPricing
from pipeline_live.data.iex.classifiers import Industry
from pipeline_live.data.alpaca.factors import (RSI,
                                               AverageDollarVolume,
                                               ExponentialWeightedMovingAverage,
                                               MovingAverageConvergenceDivergenceSignal)
from scipy.optimize import minimize
from scipy.stats import norm

api = tradeapi.REST(api_version='v2')

# Account Information
account = api.get_account()
print(account)

# Log information
log = logbook.Logger('algo')

def record(*args, **kwargs):
    print('args={}, kwargs={}'.format(args, kwargs))

def initialize(context):
    schedule_function(my_rebalance, date_rules.every_day(), time_rules.market_open(hours=1))

    schedule_function(selling, date_rules.every_day(), time_rules.market_open(hours=1))
    schedule_function(selling, date_rules.every_day(), time_rules.market_close(minutes=30))

    schedule_function(record_vars, date_rules.every_day(), time_rules.market_close())
    schedule_function(cancel_open_orders, date_rules.every_day(), time_rules.market_close(minutes=5))

    my_pipe = make_pipeline(context)
    context.attach_pipeline(my_pipe, 'my_pipeline')


def make_pipeline(context):
    # Step 1: Sector
    semicon_industry = Industry().matches('Semiconductors')
    metals_industry = Industry().matches('Precious')
    renewable_industry = Industry().matches('Alternative')

    industry_lim = (semicon_industry |
                    metals_industry |
                    renewable_industry)

    # Step 2: Price
    latest_close = USEquityPricing.close.latest
    high_price_lim = latest_close <= 1000
    low_price_lim = latest_close >= 1
    price_lim = high_price_lim & low_price_lim

    # Step 3: Volume
    dollar_volume_30D = AverageDollarVolume(window_length=30, mask=(price_lim & industry_lim))
    dollar_volume_1D = AverageDollarVolume(window_length=1, mask=(price_lim & industry_lim))
    volume_lim = dollar_volume_1D >= dollar_volume_30D

    universe = price_lim & volume_lim & industry_lim
    # Step 5: EWMA
    EWMA_15D = ExponentialWeightedMovingAverage(inputs=[USEquityPricing.close],
                                                window_length=15, decay_rate=0.94, mask=universe)
    EWMA_30D = ExponentialWeightedMovingAverage(inputs=[USEquityPricing.close],
                                                window_length=30, decay_rate=0.94, mask=universe)

    # Step 6: MACD
    MACD = EWMA_15D - EWMA_30D
    MACD_signal = MovingAverageConvergenceDivergenceSignal(inputs=[USEquityPricing.close],
                                                           fast_period=15, slow_period=30, signal_period=9,
                                                           mask=universe)
    MACD_diff = MACD - MACD_signal
    MACD_abs_diff = MACD_diff.abs()
    high_MACD_diff = MACD_abs_diff.percentile_between(91, 100)

    MACD_long = MACD < MACD_signal

    # Step 7: RSI
    RSI_15D = RSI(inputs=[USEquityPricing.close], window_length=15, mask=universe)

    RSI_long = RSI_15D < 70

    # Step 8: Securities to Trade
    longs = MACD_long & RSI_long
    securities_to_trade = longs

    return Pipeline(columns={'Longs': longs},
                    screen=(universe & securities_to_trade & high_MACD_diff))


def my_compute_weights(context, data):
    if len(context.longs) == 0:
        longs_weight = 0
    else:
        prices = data.history(context.longs, 'price', 15, '1d')
        prices = prices.sort_index(ascending=False)
        prices.columns = map(lambda x: x.symbol, prices.columns)

        daily_returns = np.log(prices / prices.shift(-1)).dropna()
        mean_returns = daily_returns.mean()
        cov_matrix = daily_returns.cov()

        def get_ret_vol_sr(weights):
            weights = np.array(weights)
            ret = np.sum(mean_returns * weights) * 252
            vol = np.sqrt(np.dot(np.transpose(weights), np.dot(cov_matrix * 252, weights)))
            sr = ret / vol
            return np.array([ret, vol, sr])

        def neg_sharpe(weights):
            return get_ret_vol_sr(weights)[2] * (-1)

        def constraint_sum(weights):
            return np.sum(weights) - 1

        def bounds_():
            lst = []
            for security in context.longs:
                lst.append((0, 1))
            return lst

        bounds = tuple(bounds_())

        def init_guess_():
            lst = []
            for security in context.longs:
                lst.append(0.25)
            return lst

        init_guess = np.array(init_guess_())

        cons = ({'type': 'eq', 'fun': constraint_sum})

        opt_results = minimize(neg_sharpe, init_guess, method='SLSQP', bounds=bounds, constraints=cons)
        weights = opt_results['x']

        longs_weight = list(np.nan_to_num(weights))

    return longs_weight

def before_trading_start(context, data):
    
    context.my_pipeline = pipeline_output('my_pipeline')
        # Longs
    context.longs = context.my_pipeline[context.my_pipeline['Longs']].index
        # Longs weights
    context.longs_weights = my_compute_weights(context, data)

def my_rebalance(context, data):
    open_orders = get_open_orders()

    for security in context.portfolio.positions:
        if security not in context.longs and data.can_trade(security):
            order_target_value(security, 0)

    count = 0
    for security in context.longs:
        if data.can_trade(security) and security not in open_orders:
            if security == context.longs[count]:
                cash_available = context.portfolio.cash
                security_value = context.longs_weights[count]*cash_available
                security_value = float(security_value)
                order_target_value(security, security_value)
                count = count + 1


def record_vars(context, data):
    long_amount = 0

    for security in context.portfolio.positions.values():
        if security.amount > 0:
            long_amount += 1

    record(Portafolio_value=context.portfolio.portfolio_value)
    record(Positions=long_amount)
    record(Cash_available=context.portfolio.cash)

def log_open_orders():
    open_orders = get_open_orders()
    if len(open_orders) == 0:
        return
    for stock, orders in open_orders.items():
        for o in orders:
            message = 'Found open order for {amount} shares in {stock}'
            log.info(message.format(amount=o.amount, stock=stock))

def cancel_open_orders(context, data):
    open_orders = get_open_orders()
    if len(open_orders) == 0:
        return
    for stock, orders in open_orders.items():
        for o in orders:
            message = 'Order for {amount} shares of {stock} was not filled. Canceling order'
            log.info(message.format(amount=o.amount, stock=stock))
            if 0 < o.amount:
                cancel_order(o)`

**Comment by shlomikushchi** [comment]
you should use the backtick notation to paste code. (backtick is ` - below the Esc key)
if you do this:
![image](https://user-images.githubusercontent.com/7924802/96506724-cc60fa00-1260-11eb-8be7-886b8dd57e56.png)

you will get this: 
```py
for security in context.longs:
    if data.can_trade(security) and security not in open_orders:
        if security == context.longs[count]:
            cash_available = context.portfolio.cash
            security_value = context.longs_weights[count]*cash_available
            security_value = float(security_value)
            order_target_value(security, security_value)
            count = count + 1
```

**Comment by shlomikushchi** [comment]
it will be much easier to read

**Comment by Nicosunaa** [comment]
So I am not getting any errors but the code is not submitting any orders as I used to do before I implemented Scipy. 

My code:

`import numpy as np
import pandas as pd
import logbook
import alpaca_trade_api as tradeapi
from pylivetrader.api import (attach_pipeline,
                              date_rules,
                              time_rules,
                              order_target_percent,
                              order_target_value,
                              get_open_orders,
                              pipeline_output,
                              get_datetime,
                              schedule_function,
                              cancel_order)
from zipline.pipeline import Pipeline
from pipeline_live.data.alpaca.pricing import USEquityPricing
from pipeline_live.data.iex.classifiers import Industry
from pipeline_live.data.alpaca.factors import (RSI,
                                               AverageDollarVolume,
                                               ExponentialWeightedMovingAverage,
                                               MovingAverageConvergenceDivergenceSignal)
from scipy.optimize import minimize
from scipy.stats import norm

def record(*args, **kwargs):
    print('args={}, kwargs={}'.format(args, kwargs))

def initialize(context):
    schedule_function(my_rebalance, date_rules.every_day(), time_rules.market_open(hours=1))

    schedule_function(selling, date_rules.every_day(), time_rules.market_open(hours=1))
    schedule_function(selling, date_rules.every_day(), time_rules.market_close(minutes=30))

    schedule_function(record_vars, date_rules.every_day(), time_rules.market_close())
    schedule_function(cancel_open_orders, date_rules.every_day(), time_rules.market_close(minutes=5))

    my_pipe = make_pipeline(context)
    context.attach_pipeline(my_pipe, 'my_pipeline')

def make_pipeline(context):
    # Step 1: Sector
    semicon_industry = Industry().matches('Semiconductors')
    metals_industry = Industry().matches('Precious')
    renewable_industry = Industry().matches('Alternative')

    industry_lim = (semicon_industry |
                    metals_industry |
                    renewable_industry)

    # Step 2: Price
    latest_close = USEquityPricing.close.latest
    high_price_lim = latest_close <= 100
    low_price_lim = latest_close >= 1
    price_lim = high_price_lim & low_price_lim

    # Step 3: Volume
    dollar_volume_30D = AverageDollarVolume(window_length=30, mask=(price_lim & industry_lim))
    dollar_volume_1D = AverageDollarVolume(window_length=1, mask=(price_lim & industry_lim))
    volume_lim = dollar_volume_1D >= dollar_volume_30D

    universe = price_lim & volume_lim & industry_lim
    # Step 5: EWMA
    EWMA_15D = ExponentialWeightedMovingAverage(inputs=[USEquityPricing.close],
                                                window_length=15, decay_rate=0.94, mask=universe)
    EWMA_30D = ExponentialWeightedMovingAverage(inputs=[USEquityPricing.close],
                                                window_length=30, decay_rate=0.94, mask=universe)

    # Step 6: MACD
    MACD = EWMA_15D - EWMA_30D
    MACD_signal = MovingAverageConvergenceDivergenceSignal(inputs=[USEquityPricing.close],
                                                           fast_period=15, slow_period=30, signal_period=9,
                                                           mask=universe)
    MACD_diff = MACD - MACD_signal
    MACD_abs_diff = MACD_diff.abs()
    high_MACD_diff = MACD_abs_diff.percentile_between(85, 100)

    MACD_long = MACD < MACD_signal

    # Step 7: RSI
    RSI_15D = RSI(inputs=[USEquityPricing.close], window_length=15, mask=universe)

    RSI_long = RSI_15D < 70

    # Step 8: Securities to Trade
    longs = MACD_long & RSI_long
    securities_to_trade = longs

    return Pipeline(columns={'Longs': longs},
                    screen=(universe & securities_to_trade & high_MACD_diff))

def my_compute_weights(context, data):
    if len(context.longs) == 0:
        longs_weight = 0
    else:
        prices = data.history(context.longs, 'price', 15, '1d')
        prices = prices.sort_index(ascending=False)
        prices.columns = map(lambda x: x.symbol, prices.columns)

        daily_returns = np.log(prices / prices.shift(-1)).dropna()
        mean_returns = daily_returns.mean()
        cov_matrix = daily_returns.cov()

        def get_ret_vol_sr(weights):
            weights = np.array(weights)
            ret = np.sum(mean_returns * weights) * 252
            vol = np.sqrt(np.dot(np.transpose(weights), np.dot(cov_matrix * 252, weights)))
            sr = ret / vol
            return np.array([ret, vol, sr])

        def neg_sharpe(weights):
            return get_ret_vol_sr(weights)[2] * (-1)

        def constraint_sum(weights):
            return np.sum(weights) - 1

        def bounds_():
            lst = []
            for security in context.longs:
                lst.append((0, 1))
            return lst

        bounds = tuple(bounds_())

        def init_guess_():
            lst = []
            for security in context.longs:
                lst.append(0.25)
            return lst

        init_guess = np.array(init_guess_())

        cons = ({'type': 'eq', 'fun': constraint_sum})

        opt_results = minimize(neg_sharpe, init_guess, method='SLSQP', bounds=bounds, constraints=cons)
        weights = opt_results['x']

        longs_weight = list(np.nan_to_num(weights))

    return longs_weight

def before_trading_start(context, data):
    context.my_pipeline = pipeline_output('my_pipeline')
    context.longs = context.my_pipeline[context.my_pipeline['Longs']].index
    context.longs_weights = my_compute_weights(context, data)
        
def my_rebalance(context, data):
    open_orders = get_open_orders()

    for security in context.portfolio.positions:
        if security not in context.longs and data.can_trade(security):
            order_target_value(security, 0)

    count = 0
    for security in context.longs:
        if data.can_trade(security) and security not in open_orders:
            if security == context.longs[count]:
                cash_available = context.portfolio.cash
                security_value = context.longs_weights[count]*cash_available
                security_value = float(security_value)
                order_target_value(security, security_value)
                #weight = float(context.longs_weights[count])
                #order_target_percent(security, weight)
                count = count + 1

def record_vars(context, data):
    long_amount = 0

    for security in context.portfolio.positions.values():
        if security.amount > 0:
            long_amount += 1

    record(Portafolio_value=context.portfolio.portfolio_value)
    record(Positions=long_amount)
    record(Cash_available=context.portfolio.cash)

def log_open_orders():
    open_orders = get_open_orders()
    if len(open_orders) == 0:
        return
    for stock, orders in open_orders.items():
        for o in orders:
            message = 'Found open order for {amount} shares in {stock}'
            log.info(message.format(amount=o.amount, stock=stock))

def cancel_open_orders(context, data):
    open_orders = get_open_orders()
    if len(open_orders) == 0:
        return
    for stock, orders in open_orders.items():
        for o in orders:
            message = 'Order for {amount} shares of {stock} was not filled. Canceling order'
            log.info(message.format(amount=o.amount, stock=stock))
            if 0 < o.amount:
                cancel_order(o)`

**Comment by Nicosunaa** [comment]
``
import numpy as np
import pandas as pd
import logbook
import alpaca_trade_api as tradeapi
from pylivetrader.api import (attach_pipeline,
                              date_rules,
                              time_rules,
                              order_target_percent,
                              order_target_value,
                              get_open_orders,
                              pipeline_output,
                              get_datetime,
                              schedule_function,
                              cancel_order)
from zipline.pipeline import Pipeline
from pipeline_live.data.alpaca.pricing import USEquityPricing
from pipeline_live.data.iex.classifiers import Industry
from pipeline_live.data.alpaca.factors import (RSI,
                                               AverageDollarVolume,
                                               ExponentialWeightedMovingAverage,
                                               MovingAverageConvergenceDivergenceSignal)
from scipy.optimize import minimize
from scipy.stats import norm

def record(*args, **kwargs):
    print('args={}, kwargs={}'.format(args, kwargs))

def initialize(context):
    schedule_function(my_rebalance, date_rules.every_day(), time_rules.market_open(hours=1))

    schedule_function(selling, date_rules.every_day(), time_rules.market_open(hours=1))
    schedule_function(selling, date_rules.every_day(), time_rules.market_close(minutes=30))

    schedule_function(record_vars, date_rules.every_day(), time_rules.market_close())
    schedule_function(cancel_open_orders, date_rules.every_day(), time_rules.market_close(minutes=5))

    my_pipe = make_pipeline(context)
    context.attach_pipeline(my_pipe, 'my_pipeline')

def make_pipeline(context):
    # Step 1: Sector
    semicon_industry = Industry().matches('Semiconductors')
    metals_industry = Industry().matches('Precious')
    renewable_industry = Industry().matches('Alternative')

    industry_lim = (semicon_industry |
                    metals_industry |
                    renewable_industry)

    # Step 2: Price
    latest_close = USEquityPricing.close.latest
    high_price_lim = latest_close <= 100
    low_price_lim = latest_close >= 1
    price_lim = high_price_lim & low_price_lim

    # Step 3: Volume
    dollar_volume_30D = AverageDollarVolume(window_length=30, mask=(price_lim & industry_lim))
    dollar_volume_1D = AverageDollarVolume(window_length=1, mask=(price_lim & industry_lim))
    volume_lim = dollar_volume_1D >= dollar_volume_30D

    universe = price_lim & volume_lim & industry_lim
    # Step 5: EWMA
    EWMA_15D = ExponentialWeightedMovingAverage(inputs=[USEquityPricing.close],
                                                window_length=15, decay_rate=0.94, mask=universe)
    EWMA_30D = ExponentialWeightedMovingAverage(inputs=[USEquityPricing.close],
                                                window_length=30, decay_rate=0.94, mask=universe)

    # Step 6: MACD
    MACD = EWMA_15D - EWMA_30D
    MACD_signal = MovingAverageConvergenceDivergenceSignal(inputs=[USEquityPricing.close],
                                                           fast_period=15, slow_period=30, signal_period=9,
                                                           mask=universe)
    MACD_diff = MACD - MACD_signal
    MACD_abs_diff = MACD_diff.abs()
    high_MACD_diff = MACD_abs_diff.percentile_between(85, 100)

    MACD_long = MACD < MACD_signal

    # Step 7: RSI
    RSI_15D = RSI(inputs=[USEquityPricing.close], window_length=15, mask=universe)

    RSI_long = RSI_15D < 70

    # Step 8: Securities to Trade
    longs = MACD_long & RSI_long
    securities_to_trade = longs

    return Pipeline(columns={'Longs': longs},
                    screen=(universe & securities_to_trade & high_MACD_diff))

def my_compute_weights(context, data):
    if len(context.longs) == 0:
        longs_weight = 0
    else:
        prices = data.history(context.longs, 'price', 15, '1d')
        prices = prices.sort_index(ascending=False)
        prices.columns = map(lambda x: x.symbol, prices.columns)

        daily_returns = np.log(prices / prices.shift(-1)).dropna()
        mean_returns = daily_returns.mean()
        cov_matrix = daily_returns.cov()

        def get_ret_vol_sr(weights):
            weights = np.array(weights)
            ret = np.sum(mean_returns * weights) * 252
            vol = np.sqrt(np.dot(np.transpose(weights), np.dot(cov_matrix * 252, weights)))
            sr = ret / vol
            return np.array([ret, vol, sr])

        def neg_sharpe(weights):
            return get_ret_vol_sr(weights)[2] * (-1)

        def constraint_sum(weights):
            return np.sum(weights) - 1

        def bounds_():
            lst = []
            for security in context.longs:
                lst.append((0, 1))
            return lst

        bounds = tuple(bounds_())

        def init_guess_():
            lst = []
            for security in context.longs:
                lst.append(0.25)
            return lst

        init_guess = np.array(init_guess_())

        cons = ({'type': 'eq', 'fun': constraint_sum})

        opt_results = minimize(neg_sharpe, init_guess, method='SLSQP', bounds=bounds, constraints=cons)
        weights = opt_results['x']

        longs_weight = list(np.nan_to_num(weights))

    return longs_weight

def before_trading_start(context, data):
    context.my_pipeline = pipeline_output('my_pipeline')
    context.longs = context.my_pipeline[context.my_pipeline['Longs']].index
    context.longs_weights = my_compute_weights(context, data)
        
def my_rebalance(context, data):
    open_orders = get_open_orders()

    for security in context.portfolio.positions:
        if security not in context.longs and data.can_trade(security):
            order_target_value(security, 0)

    count = 0
    for security in context.longs:
        if data.can_trade(security) and security not in open_orders:
            if security == context.longs[count]:
                cash_available = context.portfolio.cash
                security_value = context.longs_weights[count]*cash_available
                security_value = float(security_value)
                order_target_value(security, security_value)
                #weight = float(context.longs_weights[count])
                #order_target_percent(security, weight)
                count = count + 1

def record_vars(context, data):
    long_amount = 0

    for security in context.portfolio.positions.values():
        if security.amount > 0:
            long_amount += 1

    record(Portafolio_value=context.portfolio.portfolio_value)
    record(Positions=long_amount)
    record(Cash_available=context.portfolio.cash)

def log_open_orders():
    open_orders = get_open_orders()
    if len(open_orders) == 0:
        return
    for stock, orders in open_orders.items():
        for o in orders:
            message = 'Found open order for {amount} shares in {stock}'
            log.info(message.format(amount=o.amount, stock=stock))

def cancel_open_orders(context, data):
    open_orders = get_open_orders()
    if len(open_orders) == 0:
        return
    for stock, orders in open_orders.items():
        for o in orders:
            message = 'Order for {amount} shares of {stock} was not filled. Canceling order'
            log.info(message.format(amount=o.amount, stock=stock))
            if 0 < o.amount:
                cancel_order(o)
```

**Comment by shlomikushchi** [comment]
Hi, you can't use `pipeline_output` you need to do this: `context.pipeline_output` (and probably other api functions as well)

**Comment by Nicosunaa** [comment]
So I changed the api function for context.'api function' but it still not submitting orders. This is the message I get:

``
[2020-10-20 18:43:22.653668] INFO: Algorithm: livetrader start running with backend = alpaca data-frequency = minute
[2020-10-20 18:43:24.361314] INFO: pipeline_live.data.alpaca.pricing_loader: chart_range=56
[2020-10-20 18:43:39.808312] INFO: pipeline_live.data.alpaca.pricing_loader: chart_range=43
`` 
Even if a schedule the rabalance function for every hour, the algo still not submitting any orders. Do you think it is the scipy minimize function?

**Comment by shlomikushchi** [comment]
do you have a IEX key? you are trying to use `from pipeline_live.data.iex.classifiers import Industry`
That requires IEX api key

**Comment by Nicosunaa** [comment]
Yes,  I have been using the public IEX key. The algorithm was submitting orders normally until I started computing the weights with scipy. So, It must be something related with scipy or the weights. The algorithm works completely find in quantopian too.

**Comment by shlomikushchi** [comment]
I removed the IEX references (don't have the api key) and just did the weight calculations for all equities
it works:
![image](https://user-images.githubusercontent.com/7924802/96835274-0b06d800-144c-11eb-8201-df22d4498d17.png)

just a lot of equities
do you have a way to run this in an IDE?

**Comment by Nicosunaa** [comment]
I will remove the IEX reference and see if that's the problem. I do have PyCharm so i will run it there and I will let you know. Thanks

**Comment by Nicosunaa** [comment]
Hey, so I removed the IEX reference and put the weights in a pandas dataframe but now I am getting a different error. 

the error is:

``
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 673, in _fetch_bars_from_api_internal
    return wrapper()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 85, in wrapper
    return func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/backend/alpaca.py", line 659, in wrapper
    end=to.isoformat()).df[symbols]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/frame.py", line 2133, in __getitem__
    return self._getitem_array(key)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/frame.py", line 2177, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/indexing.py", line 1250, in _convert_to_indexer
    obj, kind=self.name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 1798, in _convert_listlike_indexer
    _, indexer = self.reindex(keyarr, level=level)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 1892, in reindex
    keep_order=False)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3299, in _join_level
    raise NotImplementedError('Index._join_level on non-unique index '
NotImplementedError: Index._join_level on non-unique index is not implemented
"""

``

**Comment by shlomikushchi** [comment]
Hi, 
could you explain the logic of the weights? maybe that will help me understand this

**Comment by Nicosunaa** [comment]
The weight are calculated so the sharpe ratio of the portafolio is maximize. Each time the pipeline throws an list of tickers, the compute_weights will compute the weight for each ticker. The problem is not with the process of computing the weights because I had the same process in Quantopian and it worked. I think that the order_target_value function is not reading the compute weights functions.

**Comment by shlomikushchi** [comment]
ok, I have an idea. could you install this branch and test it?
do this:
`pip install git+https://github.com/alpacahq/pylivetrader@untradable_assets`

**Comment by Nicosunaa** [comment]
I will try during market time and I will let you know if it works. Thanks

**Comment by Nicosunaa** [comment]
I run the algorithm with the new pylivetrader version and it is ordering but now I am getting an order error.

error:
``
[2020-10-27 17:59:02.776892] ERROR: Executor: Cannot order BVXV on 2020-10-27 17:59:00+00:00 as there is no last price for the security.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 67, in wrapper
    func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 88, in every_bar
    handle_data(algo, current_data, dt_to_use)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/misc/events.py", line 218, in handle_data
    dt,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/misc/events.py", line 237, in handle_data
    self.callback(context, data)
  File "AlgoOriginal.py", line 164, in my_rebalance
    order_target_value(security, security_value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/misc/api_context.py", line 62, in wrapped
    return getattr(algorithm, f.__name__)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 603, in order_target_value
    target_amount = self._calculate_order_value_amount(asset, target)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 842, in _calculate_order_value_amount
    self.datetime)
pylivetrader.errors.CannotOrderDelistedAsset: Cannot order BVXV on 2020-10-27 17:59:00+00:00 as there is no last price for the security.
``
Yet, BVXV should have a previous day price because It is not a new IPO.

**Comment by shlomikushchi** [comment]
try passing `quantopian_compatible=True` to algorithm instance. it might help with that.
I added 3 retires to this exact issue but it seems as if your code tried 3 times to get last price and failed all 3

**Comment by Nicosunaa** [comment]
Where in the algorithm should I put ``quantopian_compatible=True`` ? you mean that the code is not retrieving last price in the pipeline or the compute_weights functions?

**Comment by shlomikushchi** [comment]
it looks like an issue with placing an order, so it's not related to the weights
you could pass it as an argument

**Comment by Nicosunaa** [comment]
I run my algorithm with pylivetrader 0.4.0 and It worked. So, it must be something with pylivetrader 0.5.0 and 0.51.0 that is not letting me place order. I guess it is the order_target_percent function. Are there any inconveniences with this version or can I continue executing it without any problems?

**Comment by shlomikushchi** [comment]
you can work with 0.4.0 for now. I will try to understand what is the difference between the 2 versions if it really does make a difference.

**Comment by aspromatis** [comment]
Hi Shlomi - I'm trying to run a algo on the latest version of pylivetrader, but am having similar issues as other people have noted with the order_target_percent and order_target_value.  Have you been able to compare the versions and identify a work-around or fix?  Much appreciated.

**Comment by shlomikushchi** [comment]
Hi Erol, I like your work - keep it up :)
I am working with the latest version (just tested it yesterday all day with no issues).
send me a code example that you have issues with, I will execute it locally and see if there's anything different.
you could send it over here or contact me in the alpaca slack channels. 
also be sure tho check zipline-trader which adds the ability to backtest with alpaca data.

**Comment by shlomikushchi** [comment]
pylivetrader is a project that was born to be a bridge between Quantopian and Alpaca allowing users to take their written algos and run them with alpaca as a broker.
pros:
* don't need to ingest data. everything is read by using the alpaca api.
* very similar to quantopian, so if you already know how to use quantopian - you know how to use pylivetrader.

cons:
* it doesn't have a backtester
* it's not exactly like zipline. it looks like it, it feels like it but it's a bit different.

zipline-trader is a project that is based on zipline and zipline-live which takes the real quantopian's zipline and connects it to brokers (IB, Alpaca).
pros:
* it has a backtester
* it works with pyfolio and alphalens
* it has a research environment.

cons:
* you need to ingest data daily.

**Comment by shlomikushchi** [comment]
@aspromatis just an update, I ran your script and this is the log I got:
![image](https://user-images.githubusercontent.com/7924802/106051061-9f8a7180-60f0-11eb-903e-93637e98aa53.png)

looks good.

**Comment by aspromatis** [comment]
Strange, it works for me but only sporadically.  For some reason, data.current(stock, "price") is rarely able to pull in any values, and I mostly get nan.  This then causes issues with the order_target_percent calculation.  

It works sometimes, but only rarely.  There is not problem with pulling in data via data.history(stocks, 'price', etc.).

**Comment by shlomikushchi** [comment]
![image](https://user-images.githubusercontent.com/7924802/106299000-4f7ced80-625d-11eb-9b62-6899e0eec0a7.png)


your code still runs locally.. lost connection during the night, restored in the morning and kept going when market opened

**Comment by camelpac** [comment]
closing due to lack of activity
