### ISSUE TITLE
AttributeError: module 'pylivetrader.algorithm' has no attribute 'attach_pipeline'

### ISSUE THREAD

**Issue by ch01ca** [alpacahq/pylivetrader#206]
`[2020-10-22 17:24:29.618828] INFO: Algorithm: livetrader start running with backend = alpaca data-frequency = minute Traceback (most recent call last): File "/usr/local/bin/pylivetrader", line 8, in <module> sys.exit(main()) File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__ return self.main(*args, **kwargs) File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main rv = self.invoke(ctx) File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke return ctx.invoke(self.callback, **ctx.params) File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke return callback(*args, **kwargs) File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func return f(get_current_context(), *args, **kwargs) File "/usr/local/lib/python3.6/site-packages/pylivetrader/__main__.py", line 277, in run algorithm.run(retry=ctx.retry) File "/usr/local/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 268, in run self.initialize() File "/usr/local/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 228, in initialize self._initialize(self, *args, **kwargs) File "inout.py", line 41, in initialize algo.attach_pipeline(make_pipeline(context), 'pipeline') AttributeError: module 'pylivetrader.algorithm' has no attribute 'attach_pipeline'`

**Comment by ch01ca** [comment]
`Traceback (most recent call last):
  File "/usr/local/bin/pylivetrader", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/__main__.py", line 273, in run
    ctx = process_algo_params(ctx, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/__main__.py", line 189, in process_algo_params
    algomodule = get_algomodule_by_path(algofile)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/loader.py", line 50, in get_algomodule_by_path
    return get_algomodule(file, filename)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/loader.py", line 63, in get_algomodule
    exec_(code, ns)
  File "inout.py", line 21, in <module>
    from  pylivetrader.algorithm import attach_pipeline
ImportError: cannot import name 'attach_pipeline'`

**Comment by shlomikushchi** [comment]
use this example: https://github.com/alpacahq/pylivetrader/blob/master/examples/using_pipeline_live/pipeline_live_example.py

**Comment by ch01ca** [comment]
> use this example: https://github.com/alpacahq/pylivetrader/blob/master/examples/using_pipeline_live/pipeline_live_example.py

thank you
