### ISSUE TITLE
Error while running algortihm with pipeline-live

### ISSUE THREAD

**Issue by Moccazio** [alpacahq/pylivetrader#257]
Since a few days pylivetrader is not running without the following error code.

`2022-07-27 16:25:59 - Task preparing to start
Jul 27 16:27:26 [2022-07-27 16:27:26.519953] INFO: Algorithm: livetrader start running with backend = alpaca data-frequency = minute
Jul 27 16:27:33 [2022-07-27 16:27:33.818260] INFO: pipeline_live.data.alpaca.pricing_loader: chart_range=44
Jul 27 16:27:58 /home/Moccazio/.zipline/data/dailycache/alpaca_chart_44: digest mismatch 6a135cb50f67f8572984d722041fcaf0 != 2d63b556c8baa5e1155fc559a23634b7, reloading
Jul 27 16:27:58 [2022-07-27 16:27:58.453560] DEBUG: pipeline_live.data.sources.util: fetch: 10.82% completed
Jul 27 16:28:19 [2022-07-27 16:28:19.275132] DEBUG: pipeline_live.data.sources.util: fetch: 21.65% completed
Jul 27 16:28:21 [2022-07-27 16:28:21.160292] DEBUG: pipeline_live.data.sources.util: fetch: 30.67% completed
Jul 27 16:28:38 [2022-07-27 16:28:38.028209] DEBUG: pipeline_live.data.sources.util: fetch: 41.49% completed
Jul 27 16:28:38 [2022-07-27 16:28:38.816424] DEBUG: pipeline_live.data.sources.util: fetch: 50.51% completed
Jul 27 16:28:55 [2022-07-27 16:28:55.334823] DEBUG: pipeline_live.data.sources.util: fetch: 61.34% completed
Jul 27 16:28:56 [2022-07-27 16:28:56.136682] DEBUG: pipeline_live.data.sources.util: fetch: 70.36% completed
Jul 27 16:29:15 [2022-07-27 16:29:15.933028] DEBUG: pipeline_live.data.sources.util: fetch: 81.18% completed
Jul 27 16:29:17 [2022-07-27 16:29:17.018806] DEBUG: pipeline_live.data.sources.util: fetch: 90.20% completed
Jul 27 16:29:27 Traceback (most recent call last):
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 223, in _one_request
Jul 27 16:29:27     resp.raise_for_status()
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/requests/models.py", line 960, in raise_for_status
Jul 27 16:29:27     raise HTTPError(http_error_msg, response=self)
Jul 27 16:29:27 requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://data.alpaca.markets/v2/stocks/BCH/USD/bars?timeframe=1Day&adjustment=raw&start=2022-06-13&limit=44
Jul 27 16:29:27 During handling of the above exception, another exception occurred:
Jul 27 16:29:27 Traceback (most recent call last):
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/bin/pylivetrader", line 8, in <module>
Jul 27 16:29:27     sys.exit(main())
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
Jul 27 16:29:27     return self.main(*args, **kwargs)
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/click/core.py", line 1062, in main
Jul 27 16:29:27     rv = self.invoke(ctx)
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/click/core.py", line 1668, in invoke
Jul 27 16:29:27     return _process_result(sub_ctx.command.invoke(sub_ctx))
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
Jul 27 16:29:27     return ctx.invoke(self.callback, **ctx.params)
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/click/core.py", line 763, in invoke
Jul 27 16:29:27     return __callback(*args, **kwargs)
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/click/decorators.py", line 26, in new_func
Jul 27 16:29:27     return f(get_current_context(), *args, **kwargs)
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pylivetrader/__main__.py", line 277, in run
Jul 27 16:29:27     algorithm.run(retry=ctx.retry)
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 275, in run
Jul 27 16:29:27     return self.executor.run(retry=retry)
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 119, in run
Jul 27 16:29:27     algo.before_trading_start(self.current_data)
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 248, in before_trading_start
Jul 27 16:29:27     self._before_trading_start(self, data)
Jul 27 16:29:27   File "long_short_pipeline_algo.py", line 53, in before_trading_start
Jul 27 16:29:27     context.output = context.pipeline_output('my_pipeline')
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 1095, in pipeline_output
Jul 27 16:29:27     output = eng.run_pipeline(self._pipelines[name])
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pipeline_live/engine.py", line 77, in run_pipeline
Jul 27 16:29:27     initial_workspace,
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pipeline_live/engine.py", line 244, in compute_chunk
Jul 27 16:29:27     to_load, mask_dates, symbols, mask,
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pipeline_live/data/alpaca/pricing_loader.py", line 42, in load_adjusted_array
Jul 27 16:29:27     prices = alpaca.get_stockprices(chart_range)
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pipeline_live/data/sources/alpaca.py", line 20, in get_stockprices
Jul 27 16:29:27     return get_stockprices_cached(all_symbols)
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pipeline_live/data/sources/util.py", line 68, in wrapper
Jul 27 16:29:27     body = func(*args, **kwargs)
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pipeline_live/data/sources/alpaca.py", line 18, in get_stockprices_cached
Jul 27 16:29:27     return _get_stockprices(all_symbols, limit, timespan)
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pipeline_live/data/sources/alpaca.py", line 63, in _get_stockprices
Jul 27 16:29:27     return parallelize(fetch, splitlen=199)(symbols)
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pipeline_live/data/sources/util.py", line 30, in wrapper
Jul 27 16:29:27     task_result = task.result()
Jul 27 16:29:27   File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
Jul 27 16:29:27     return self.__get_result()
Jul 27 16:29:27   File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
Jul 27 16:29:27     raise self._exception
Jul 27 16:29:27   File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Jul 27 16:29:27     result = self.fn(*self.args, **self.kwargs)
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/pipeline_live/data/sources/alpaca.py", line 46, in fetch
Jul 27 16:29:27     adjustment='raw'
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 748, in get_bars
Jul 27 16:29:27     raw=True))
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 728, in get_bars_iter
Jul 27 16:29:27     for bar in bars:
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 648, in _data_get
Jul 27 16:29:27     resp = self.data_get(path, data=data, api_version=api_version)
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 256, in data_get
Jul 27 16:29:27     'GET', path, data, base_url=base_url, api_version=api_version,
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 202, in _request
Jul 27 16:29:27     return self._one_request(method, url, opts, retry)
Jul 27 16:29:27   File "/home/Moccazio/.virtualenvs/ziplive36/lib/python3.6/site-packages/alpaca_trade_api/rest.py", line 231, in _one_request
Jul 27 16:29:27     raise APIError(error, http_error)
Jul 27 16:29:27 alpaca_trade_api.rest.APIError: endpoint not found`

**Comment by vinceperkins** [comment]
I edited the files to fix the issue here: https://github.com/vinceperkins/pipeline-live/commit/396a1771af5540554d485836f94a08e77c55996f. It currently works with that repository. I submitted a pull request for the official repository.
