### ISSUE TITLE
KeyError on pylivetrader restart

### ISSUE THREAD

**Issue by ttt733** [alpacahq/pylivetrader#62]
It was reported that when pylivetrader's execution is interrupted (E.g. with a Ctrl-C) and restarted, it can encounter a KeyError:
```
C:\ap>pylivetrader run -f paper50.py 2>>&1 | tee output50.txt

[2018-12-11 09:59:12.829549-0500] INFO: : AP

[2018-12-11 09:59:12.845149-0500] INFO: Algorithm: livetrader start running with backend = alpaca data-frequency = minute

Traceback (most recent call last):

  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "c:\python36\lib\runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "C:\Python36\Scripts\pylivetrader.exe\__main__.py", line 9, in <module>

  File "c:\python36\lib\site-packages\click\core.py", line 764, in __call__

    return self.main(*args, **kwargs)

  File "c:\python36\lib\site-packages\click\core.py", line 717, in main

    rv = self.invoke(ctx)

  File "c:\python36\lib\site-packages\click\core.py", line 1137, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "c:\python36\lib\site-packages\click\core.py", line 956, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "c:\python36\lib\site-packages\click\core.py", line 555, in invoke

    return callback(*args, **kwargs)

  File "c:\python36\lib\site-packages\click\decorators.py", line 17, in new_func

    return f(get_current_context(), *args, **kwargs)

  File "c:\python36\lib\site-packages\pylivetrader\__main__.py", line 144, in run

    algorithm.run(retry=ctx.retry)

  File "c:\python36\lib\site-packages\pylivetrader\algorithm.py", line 242, in run

    return self.executor.run(retry=retry)

  File "c:\python36\lib\site-packages\pylivetrader\executor\executor.py", line 120, in run

    algo.before_trading_start(self.current_data)

  File "c:\python36\lib\site-packages\pylivetrader\algorithm.py", line 215, in before_trading_start

    self._before_trading_start(self, data)

  File "paper50.py", line 236, in before_trading_start

    c.pipe = pipeline_output('pipe')

  File "c:\python36\lib\site-packages\pylivetrader\misc\api_context.py", line 62, in wrapped

    return getattr(algorithm, f.__name__)(*args, **kwargs)

  File "c:\python36\lib\site-packages\pylivetrader\algorithm.py", line 1049, in pipeline_output

    output = eng.run_pipeline(self._pipelines[name])

KeyError: 'pipe'
```
The error goes away with state file deletion. We should find the root cause of the issue and fix it.

**Comment by shlomikushchi** [comment]
this was resolved by adding the `can_load()` check to the pickled file. https://github.com/alpacahq/pylivetrader/commit/b01e25d02002cfc1ff42816c926ccf76a465741e
closing this issue. for now
