### ISSUE TITLE
Pickling instances of user-defined classes with StateStore fails

### ISSUE THREAD

**Issue by 11k** [alpacahq/pylivetrader#78]
I have a class called `JPosition` defined in my `algo.py` file so I can more comfortably track certain things about the positions I take.
```
class JPostition:
    def __init__(self,
                 asset,
                 entry_price=None,
                 averaged_down=False,
                 complete=False):
        self.asset = asset
        self.entry_price = entry_price 
        self.averaged_down = averaged_down
        self.complete = complete

    def percent_change(self, current_price):
        return (current_price - self.entry_price) / current_price
```

I store instances of `JPosition` in `context` within a dictionary where `Asset`s are keys.
```
def before_trading_start(context, data):
    context.j_positions = {}

    tickers = ["SNAP", "MU", "AMD"]
    for ticker in tickers:
        s = symbol(ticker)
        context.j_positions[s] = JPostition(s)
```

Every time pylivetrader attempts to pickle `context` via its state management functionality, an exception is raised.
```
Traceback (most recent call last):
  File "/usr/local/bin/pylivetrader", line 10, in <module>                                                                
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__                                      
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main                                          
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke                                       
    return _process_result(sub_ctx.command.invoke(sub_ctx))                                                               
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke                                        
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke                                        
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func                                 
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/__main__.py", line 153, in run                                
    algorithm.run(retry=ctx.retry)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 252, in run                               
    return self.executor.run(retry=retry)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/executor/executor.py", line 120, in run                       
    algo.before_trading_start(self.current_data)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/algorithm.py", line 227, in before_trading_start              
    self, self._algoname, self._context_persistence_excludes)                                                             
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/statestore/__init__.py", line 42, in save                     
    pickle.dump(state, f)
_pickle.PicklingError: Can't pickle <class 'JPostition'>: attribute lookup JPostition on builtins failed    
```

Here's what `state` is just before the exception is raised.
```
{
    'j_positions': {
        Asset(83e52ac1-bb18-4e9f-b68d-dda5a8af3ec0, symbol=SNAP, asset_name=SNAP, exchange=NYSE): <JPostition object at 0x7f0f111b7fd0>,
        Asset(1ef18995-5094-4f62-a5c5-e00168611152, symbol=MU, asset_name=MU, exchange=NASDAQ): <JPostition object at 0x7f0f14e95a90>,
        Asset(03fb07bb-5db1-4077-8dea-5d711b272625, symbol=AMD, asset_name=AMD, exchange=NASDAQ): <JPostition objectat 0x7f0f111b7f28>
    },
    'datetime': Timestamp('2019-02-07 14:06:00+0000', tz='UTC'),
    '__state_checksum': 'algo'
}
```

I'd really like to continue using the built-in state management, but couldn't figure out why this was happening. I just added `j_positions` to the list of exclusions in the meantime.
```
def initialize(context):
    log.info("Initializing")
    # Pickling instances of user-defined classes fails.
    context._context_persistence_excludes.append("j_positions")
```

**Comment by jpb8** [comment]
@11k have you found a solution for this issue yet? I am running into the same issue.

**Comment by 11k** [comment]
Sorry, it's been a long time and I've since moved on to other things. I never figured out why this was happening so I just did my best to work around the problem. Don't remember exactly what I did, though. 🤦‍♂️

**Comment by shlomikushchi** [comment]
I ran the exact same code locally and everything seems fine.
![image](https://user-images.githubusercontent.com/7924802/79251931-85e1ab80-7e89-11ea-8375-ae2fef389164.png)


I defined the object exactly like you did:
![image](https://user-images.githubusercontent.com/7924802/79251981-97c34e80-7e89-11ea-84f1-4ca44c5c81da.png)


does anyone still experience this issue (with the latest version of pylivetrader. install it from github) ?

**Comment by shlomikushchi** [comment]
I am closing this issue for now. let me know if something is still nto working properly
