### ISSUE TITLE
ImportError: cannot import name 'attach_pipeline'

### ISSUE THREAD

**Issue by Govern0r** [alpacahq/pylivetrader#79]
The import I'm using:

`from pylivetrader.algorithm import attach_pipeline, pipeline_output`

Even when I install pipeline-live in my Dockerfile, it seems to throw this error:

```
/usr/local/lib/python3.6/site-packages/IPython/frontend.py:21: ShimWarning: The top-level `frontend` package has been deprecated since IPython 1.0. All its subpackages have been moved to the top `IPython` level.
  "All its subpackages have been moved to the top `IPython` level.", ShimWarning)
Traceback (most recent call last):
  File "/usr/local/bin/pylivetrader", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/__main__.py", line 131, in run
    ctx = process_algo_params(ctx, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/__main__.py", line 106, in process_algo_params
    algomodule = get_algomodule_by_path(algofile)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/loader.py", line 50, in get_algomodule_by_path
    return get_algomodule(file, filename)
  File "/usr/local/lib/python3.6/site-packages/pylivetrader/loader.py", line 63, in get_algomodule
    exec_(code, ns)
  File "algo.py", line 40, in <module>
    from pylivetrader.algorithm import attach_pipeline, pipeline_output
ImportError: cannot import name 'attach_pipeline'
```

(Running in Docker: alpacamarkets/pylivetrader:0.0.13)

Here's my Dockerfile:

```
FROM alpacamarkets/pylivetrader:0.0.13

RUN mkdir /app
COPY . /app
WORKDIR /app

RUN pip install pipeline-live

CMD pylivetrader run -f algo.py
```

**Comment by ttt733** [comment]
Hello @Govern0r , since you've filed this issue, we've updated the dockerhub image - it was lagging behind on releases. Could you please try again with the latest (v0.0.25) image and see if it works?

**Comment by davidschlender** [comment]
Any updates on this? I too have the line,

`from quantopian.algorithm import attach_pipeline, pipeline_output` 

that I was trying to replace with `zipline`, until I found this [migration guide](https://github.com/alpacahq/pylivetrader/blob/master/migration.md) that suggested to replace `quantopian` with `pylivetrader`. However,

`from pylivetrader.algorithm import attach_pipeline, pipeline_output` doesn't work.

**Comment by ttt733** [comment]
Hi @davidschlender , please try using `from pylivetrader.api import attach_pipeline, pipeline_output`.
